import Link from 'next/link';

export default function DahshaCase({params}:{params:{locale:'ar'|'en'}}){
 const ar=params.locale==='ar';
 return <main dir={ar?'rtl':'ltr'} style={{background:'#fff5e5',color:'#171625',minHeight:'100vh'}}>
  <header style={{padding:'28px clamp(22px,6vw,90px)',display:'flex',justifyContent:'space-between',alignItems:'center',borderBottom:'1px solid rgba(23,22,37,.12)'}}><b>ATHR BRANDS</b><Link href={`/${params.locale}#work`} style={{color:'#2d5be7'}}>{ar?'العودة إلى الأعمال':'Back to work'}</Link></header>
  <section style={{padding:'clamp(70px,10vw,150px) clamp(22px,8vw,130px)',display:'grid',gap:32,background:'#191824',color:'#fff'}}><small style={{color:'#ffd43b'}}>05 · {ar?'مشروع تصوري':'CONCEPT PROJECT'}</small><h1 style={{fontSize:'clamp(70px,14vw,190px)',margin:0,lineHeight:.9}}>{ar?'دهشة':'DAHSHA'}</h1><h2 style={{fontSize:'clamp(28px,5vw,66px)',maxWidth:900,margin:0}}>{ar?'مرح يراه الطفل، وهوية يطمئن لها الوالد.':'Joy a child sees. A brand a parent trusts.'}</h2></section>
  <section style={{padding:'clamp(60px,8vw,120px) clamp(22px,8vw,130px)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:30}}><div><small style={{color:'#2d5be7'}}>01 · {ar?'الفكرة':'CONCEPT'}</small><h2 style={{fontSize:'clamp(38px,6vw,80px)'}}>{ar?'دهشة: لحظة الاكتشاف.':'DAHSHA: the moment of discovery.'}</h2></div><p style={{fontSize:20,lineHeight:2}}>{ar?'هوية لمتجر ألعاب وتجارب للأطفال من 4 إلى 10 سنوات، تبني عالمها حول الفضول والاختيار والخيال. التحدي كان صناعة علامة مرحة ومميزة من دون الوقوع في القوالب الطفولية المستهلكة.':'An identity for a children’s play and discovery store, ages 4–10, built around curiosity, choice and imagination without falling into tired childish clichés.'}</p></section>
  <section style={{padding:'clamp(60px,8vw,120px) clamp(22px,8vw,130px)',background:'#2d5be7',color:'#fff'}}><small>02 · {ar?'منصة العلامة':'BRAND PLATFORM'}</small><h2 style={{fontSize:'clamp(40px,7vw,90px)',maxWidth:1000}}>{ar?'متعة الاكتشاف: فضول + ثقة + خيال + بساطة + طرح.':'The joy of discovery: curiosity, confidence, imagination, simplicity and play.'}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:14}}>{(ar?['الطاقة','الرسالة','الوعد','الفضول','الثقة','الخيال']:['Energy','Message','Promise','Curiosity','Confidence','Imagination']).map(x=><div key={x} style={{padding:24,background:'#fff',color:'#171625',borderRadius:18,fontWeight:700}}>{x}</div>)}</div></section>
  <section style={{padding:'clamp(60px,8vw,120px) clamp(22px,8vw,130px)'}}><small style={{color:'#2d5be7'}}>03 · {ar?'النظام البصري':'VISUAL SYSTEM'}</small><h2 style={{fontSize:'clamp(40px,7vw,90px)'}}>{ar?'مشرقة، لكن محسوبة.':'Bright, but considered.'}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',height:180,borderRadius:22,overflow:'hidden'}}>{['#2558E8','#FFD438','#FF6B5F','#25C7B7','#7C4DFF','#19182A'].map(c=><i key={c} style={{background:c}} />)}</div><p style={{fontSize:20,lineHeight:2,maxWidth:900}}>{ar?'الألوان تؤدي وظائف محددة داخل النظام، مع مساحة كريمية واسعة تمنع الهوية من التحول إلى ضوضاء بصرية. العناصر الهندسية البسيطة تصنع المفاجأة وتتحول إلى نمط قابل للتوسع.':'Colors have defined roles, balanced by generous cream space. Simple geometric elements create surprise and become a scalable pattern.'}</p></section>
  <section style={{padding:'clamp(60px,8vw,120px) clamp(22px,8vw,130px)',background:'#191824',color:'#fff'}}><small style={{color:'#ffd43b'}}>04 · {ar?'التجربة':'EXPERIENCE'}</small><h2 style={{fontSize:'clamp(40px,7vw,90px)',maxWidth:1000}}>{ar?'فعل حقيقي، لا وضعية مصطنعة.':'Real action, never staged.'}</h2><p style={{fontSize:20,lineHeight:2,maxWidth:900}}>{ar?'التطبيقات والصور تُظهر الطفل وهو يبني ويجرب ويكتشف ويشارك. الهوية تمتد إلى الأكياس، بطاقات الاكتشاف، المتجر، المحتوى الرقمي والمراسلات من دون أن تفقد وضوحها.' :'Applications and imagery show children building, testing, discovering and sharing. The identity extends to bags, discovery cards, retail, digital content and stationery without losing clarity.'}</p></section>
  <footer style={{padding:'50px clamp(22px,8vw,130px)',display:'flex',justifyContent:'space-between'}}><b>DAHSHA · ATHR BRANDS 2026</b><Link href={`/${params.locale}#work`} style={{color:'#2d5be7'}}>{ar?'العودة إلى الأعمال':'Back to work'}</Link></footer>
 </main>
}
