import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Locale } from '@/content/site';
import { FeasibilityFrame, DataTable } from '@/components/feasibility/FeasibilityFrame';
import { FeasibilityCalculator } from '@/components/feasibility/FeasibilityCalculator';
import { BASE_INPUTS, FIXED_COSTS, SETUP_COSTS, SCENARIOS, calculateFeasibility } from '@/lib/feasibility-model';
import { feasibilityMetadata } from '@/lib/feasibility-metadata';
import styles from '@/components/feasibility/Feasibility.module.css';

export function generateMetadata({ params }: { params: { locale: Locale } }) {
  return feasibilityMetadata(params.locale, true);
}

export default function SumraFeasibilityPage({ params }: { params: { locale: Locale } }) {
  const { locale } = params;
  if (locale !== 'ar' && locale !== 'en') notFound();
  const t = (ar: string, en: string) => locale === 'ar' ? ar : en;
  const format = (value: number) => new Intl.NumberFormat(locale === 'ar' ? 'ar-SA-u-nu-latn' : 'en-GB', { maximumFractionDigits: 0 }).format(value);
  const amount = (value: number) => <bdi>{format(value)}</bdi>;
  const base = calculateFeasibility(BASE_INPUTS);
  const chapters = [
    ['decision', t('الملخص وحدود الدراسة', 'Summary and scope')],
    ['market', t('السوق والعميل', 'Market and customer')],
    ['offer', t('العرض ونموذج الإيراد', 'Offer and revenue model')],
    ['operations', t('التشغيل والطاقة', 'Operations and capacity')],
    ['assumptions', t('سجل الافتراضات', 'Assumptions register')],
    ['budget', t('التأسيس والتكاليف', 'Setup and costs')],
    ['financial-model', t('النموذج المالي', 'Financial model')],
    ['risks', t('المخاطر وقرار المضي', 'Risks and decision gates')],
    ['brand', t('من الجدوى إلى الهوية', 'From feasibility to identity')],
    ['sources', t('المصادر والتحديث', 'Sources and updates')],
  ];
  return <FeasibilityFrame locale={locale} path="/work/sumra/feasibility" project={{ slug: 'sumra', name: t('سُمرة', 'SUMRA') }}>
    <section className={styles.hero}>
      <div><p className={styles.eyebrow}>{t('سُمرة · نموذج دراسة جدوى تصوري', 'SUMRA · Illustrative feasibility study')}</p><h1>{t('قبل أول فنجان، نختبر الفكرة.', 'Before the first cup, test the idea.')}</h1>
        <p className={styles.lead}>{t('دراسة لفرع مقهى صغير تربط العميل والتشغيل والتكلفة بقرارات العلامة. اقرأ المنطق، راجع الافتراضات، وغيّر الأرقام بنفسك.', 'A small café branch study connecting customers, operations and costs to brand decisions. Explore the reasoning, inspect the assumptions and change the numbers yourself.')}</p>
        <div className={styles.actions}><a className={`${styles.button} ${styles.buttonFilled}`} href="#financial-model">{t('جرّب حاسبة الجدوى', 'Try the feasibility calculator')}</a><Link className={styles.button} href={`/${locale}/work/sumra`}>{t('استراتيجية سُمرة وهويتها', 'SUMRA strategy and identity')}</Link></div>
      </div>
      <figure><Image src="/assets/studies/sumra/full-v2.webp" alt={t('تطبيقات هوية سُمرة التصورية على أكياس البن والأكواب', 'Conceptual SUMRA identity on coffee bags and cups')} width={1536} height={1024} priority sizes="(max-width: 900px) 100vw, 50vw" /><figcaption>{t('هوية سُمرة التصورية من أثر · كل حبة لها سُمرتها.', 'The SUMRA identity concept by ATHR · Every bean has its own roast.')}</figcaption></figure>
    </section>
    <div className={styles.notice}><p><strong>{t('افتراضات معلنة، وليست نتائج سوق أو تشغيل.', 'Disclosed assumptions, not market or operating results.')}</strong> {t('سُمرة مشروع تصوري. لم يُنفّذ مسح ميداني أو افتتاح، ولم تُجمع عروض أسعار لهذا المثال. الأرقام التجارية تعليمية، والمراجع الرسمية أدناه توثّق معدل الضريبة ومنهج الحساب فقط. إصدار النموذج: 6 سبتمبر 2026.', 'SUMRA is a concept project. No field survey, opening or supplier-quotation exercise has been completed for this example. Commercial figures are illustrative; the official references below support the VAT rate and calculation method only. Model version: 6 September 2026.')}</p></div>
    <div className={styles.body}>
      <nav className={styles.contents} aria-label={t('فهرس دراسة الجدوى', 'Feasibility study contents')}>{chapters.map(([id, title], index) => <a key={id} href={`#${id}`}>{String(index + 1).padStart(2, '0')} · {title}</a>)}</nav>

      <section id="decision" className={styles.section}><span className={styles.sectionNumber}>01</span><h2>{t('ما القرار الذي ندرسه؟', 'What decision are we examining?')}</h2>
        <p>{t('هل يمكن تشغيل فرع أول لسُمرة في موقع افتراضي بالقصيم، بقائمة مركزة ومبيعات مباشرة للأفراد، مع تمويل يغطي التجهيز والتدرّج؟ لم يُختر موقع فعلي؛ أرقام الإيجار والأجور والطلب ليست متوسطات سوقية للمنطقة.', 'Could SUMRA operate a first branch at a hypothetical Qassim location, with a focused menu and direct retail sales, while funding setup and ramp-up? No actual site has been selected. Rent, payroll and demand figures are not regional market benchmarks.')}</p>
        <p>{t('النطاق المالي: مقهى يشتري البن المحمّص من مورد ويبيع المشروبات وأكياس البن وبعض المخبوزات الجاهزة. هوية سُمرة تشمل فكرة المحمصة والمقهى؛ هذا المثال لا يتضمن مصنع تحميص أو مبيعات جملة أو مطبخ إنتاج. التوسع إلى التحميص الداخلي يحتاج تجهيزات وتشغيلًا ودراسة إضافية.', 'Financial scope: a café buying roasted beans from a supplier and selling drinks, retail coffee bags and selected ready-made bakery items. SUMRA’s identity spans a roastery and café concept; this example excludes a roasting plant, wholesale and a production kitchen. In-house roasting requires additional equipment, operations and a separate study.')}</p>
        <dl className={styles.metrics}>
          <div className={styles.metric}><dt>{t('تمويل السيناريو الأساسي', 'Base-case initial funding')}</dt><dd>{amount(base.funding)}<small>{t('ر.س ضمن نطاق النموذج', 'SAR within model scope')}</small></dd></div>
          <div className={styles.metric}><dt>{t('التعادل التشغيلي الأساسي', 'Base operating break-even')}</dt><dd>{amount(base.breakEvenWholeDaily)}<small>{t('فاتورة يوميًا عند متوسط 28 ر.س شامل الضريبة', 'daily transactions at SAR 28 including VAT')}</small></dd></div>
          <div className={styles.metric}><dt>{t('السنة الأولى في السيناريو الأساسي', 'Base-case first year')}</dt><dd className={styles.negative}>{amount(base.yearOperatingSurplus)}<small>{t('ر.س عجز تشغيلي قبل الإهلاك والتمويل والزكاة والضرائب', 'SAR operating deficit before depreciation, financing, Zakat and income tax')}</small></dd></div>
        </dl>
        <p className={styles.note}>{t(`قراءة النتيجة الأساسية: فائض الشهر المستقر نحو ${format(base.operatingSurplus)} ر.س، لكن التدرّج يجعل السنة الأولى قريبة من التعادل التشغيلي. الفكرة تحتاج إثبات الطلب وضبط التكلفة قبل التزام طويل بالإيجار والتجهيز؛ هذا المثال لا يصدر توصية استثمار نهائية.`, `Base-case reading: the steady-state month produces about SAR ${format(base.operatingSurplus)} in operating surplus, but ramp-up leaves the first year near operating break-even. Demand and costs need validation before a long lease or fit-out commitment. This example does not issue a final investment recommendation.`)}</p>
      </section>

      <section id="market" className={styles.section}><span className={styles.sectionNumber}>02</span><h2>{t('السوق يبدأ بفرضيات قابلة للاختبار.', 'Start with market hypotheses you can test.')}</h2>
        <DataTable caption={t('فرضيات الجمهور والطلب — لم تُختبر ميدانيًا', 'Customer and demand hypotheses — not field-tested')} headers={[t('الفرضية', 'Hypothesis'), t('ما نحتاج معرفته', 'What we need to learn'), t('طريقة التحقق المقترحة', 'Proposed validation')]} rows={[
          [t('عميل يومي قريب', 'Nearby daily customer'), t('هل توجد حركة متكررة في الصباح وأوقات الاستراحة؟ وما صعوبة الوقوف والاستلام؟', 'Is there recurring morning and break-time demand? How easy are parking and pickup?'), t('عدّ الحركة في مواقع مرشحة عبر أيام عمل وعطلة، مع تسجيل الساعة والطقس والأحداث المؤثرة.', 'Count activity at candidate sites on weekdays and weekends, recording time, weather and unusual events.')],
          [t('عميل يهتم بالطعم الواضح', 'Customer seeking clear flavour choices'), t('هل يفهم درجات التحميص؟ وهل يفضّل مساعدة بسيطة على الاختيار؟', 'Do customers understand roast levels, and do they value simple guidance?'), t('مقابلات استطلاعية وتذوق واختبار قائمة؛ تُوثق الإجابات الفعلية ولا تُعمم إحصائيًا من عينة صغيرة.', 'Exploratory interviews, tastings and menu tests. Record actual responses without claiming statistical representation from a small sample.')],
          [t('مشتري البن للمنزل', 'Home-coffee buyer'), t('ما معدل إعادة الشراء والحجم والطحنة المطلوبة؟ وهل تكلفة التغليف تسمح بهامش مناسب؟', 'What are repeat purchase, pack size and grind preferences? Does packaging leave adequate margin?'), t('اختبار بيع محدود بأكياس فعلية وتسجيل تكلفة كل منتج والفاتورة والعودة للشراء.', 'Run a limited paid bag-sales test and record product cost, transaction value and repeat purchases.')],
        ]} />
        <h3>{t('كيف نقارن المنافسين؟', 'How would we compare competitors?')}</h3>
        <p>{t('نقارن المقاهي المختصة والسلاسل والمخابز التي تبيع القهوة في نطاق الوصول الفعلي للمواقع المرشحة. يسجل كل رصد اسم الفرع والتاريخ وسعر سلة متطابقة شاملة الضريبة، وحجم المنتج، وساعات العمل، وتجربة الطلب والانتظار. لا نضع أسماء أو أسعار منافسين غير متحقق منها.', 'Compare specialty cafés, chains and coffee-serving bakeries within the actual catchment of candidate sites. Each observation records the branch, date, a like-for-like VAT-inclusive basket, portion sizes, hours, ordering and waiting experience. No unverified competitor names or prices are supplied here.')}</p>
        <p>{t('نقدّر الطلب من عدد الزيارات الممكنة × التحويل إلى شراء، ثم نتحقق من متوسط الفواتير وتوزيعها بالساعة. مشاهدة المارة أو عدد متابعي الحساب لا يساوي طلبًا مدفوعًا. افتراض 90 فاتورة يوميًا في النموذج يحتاج اختبار بيع وقياس عودة العميل.', 'Estimate demand from reachable visits × purchase conversion, then validate average transactions and hourly distribution. Passer-by counts or social followers are not paid demand. The model’s 90 daily transactions require a paid sales test and repeat-customer measurement.')}</p>
      </section>

      <section id="offer" className={styles.section}><span className={styles.sectionNumber}>03</span><h2>{t('عرض صغير يمكن ضبط جودته وتكلفته.', 'A focused offer with controllable quality and cost.')}</h2>
        <div className={styles.grid}>
          <article className={styles.card}><h3>{t('القائمة المقترحة', 'Proposed menu')}</h3><p>{t('مشروبات إسبرسو وترشيح، خيارات حليب واضحة، مخبوزات محدودة من مورد، وأكياس بن للمنزل. تُراجع الوصفات والأوزان والهدر لكل صنف قبل اعتماد سعره.', 'Espresso and filter drinks, clear milk choices, a limited outsourced bakery range and retail bean bags. Review recipes, weights and waste for each item before setting its price.')}</p></article>
          <article className={styles.card}><h3>{t('مصدر الإيراد في النموذج', 'Revenue included in the model')}</h3><p>{t('فواتير البيع المباشر داخل الفرع والاستلام. متوسط 28 ر.س يشمل سلة المشروبات والإضافات والأكياس مجتمعة، وليس سعر كوب واحد. لا يفترض النموذج دخل اشتراكات أو جملة أو عمولات تطبيقات توصيل.', 'Direct in-store and pickup transactions. The SAR 28 average combines drinks, add-ons and bean bags; it is not a single-cup price. Subscriptions, wholesale and delivery-platform commissions are not included.')}</p></article>
        </div>
        <p>{t('نبني لاحقًا متوسط الفاتورة من مزيج أصناف وكميات وأسعار مثبتة في اختبار البيع. نسبة التكلفة المتغيرة 35% تبسيط لهذا المزيج وتشمل المواد والتغليف والهدر ورسوم الدفع؛ تغير المزيج أو إضافة التوصيل يستلزم إعادة حسابها.', 'A later model should derive the average transaction from an observed product mix, quantities and prices. The 35% variable cost is a blended simplification including ingredients, packaging, waste and payment fees. A different mix or delivery channel requires recalculation.')}</p>
      </section>

      <section id="operations" className={styles.section}><span className={styles.sectionNumber}>04</span><h2>{t('نربط المبيعات بقدرة الفرع على خدمتها.', 'Match sales to the branch’s ability to serve them.')}</h2>
        <DataTable caption={t('تصور التشغيل ومتطلبات التحقق', 'Operating concept and required validation')} headers={[t('المحور', 'Area'), t('التصور الأولي', 'Initial concept'), t('قبل الاعتماد', 'Before approval')]} rows={[
          [t('الموقع', 'Site'), t('فرع صغير بقائمة مركزة ومسار واضح للطلب والاستلام.', 'A small branch with a focused menu and clear ordering and pickup flow.'), t('معاينة الوصول والمواقف والتمديدات ومتطلبات النشاط، والحصول على عرض إيجار مكتوب.', 'Inspect access, parking, utilities and activity requirements; obtain a written rent offer.')],
          [t('الفريق', 'Team'), t('ميزانية أجور 24,000 ر.س شهريًا: 6,000 للمالك العامل/المدير و18,000 لبقية الفريق وتكاليف توظيفه.', 'SAR 24,000 monthly payroll budget: 6,000 for the working owner/manager and 18,000 for the crew and employment costs.'), t('إعداد جدول ورديات وأدوار وأيام راحة وتكلفة شاملة؛ الرقم ميزانية افتراضية وليس عرض توظيف.', 'Create shifts, roles, rest-day coverage and fully loaded costs; these are assumed budgets, not employment offers.')],
          [t('الطاقة', 'Capacity'), t('حد تخطيطي 150 فاتورة يوميًا في الحاسبة، مع 90 فاتورة في السيناريو الأساسي.', 'An assumed limit of 150 daily transactions in the calculator, with 90 in the base case.'), t('اختبار الخدمة في الذروة وقياس زمن الطلب والتحضير والتسليم؛ المتوسط اليومي وحده لا يثبت القدرة.', 'Test peak service and measure ordering, preparation and handoff time. A daily average alone does not establish capacity.')],
          [t('الموردون والجودة', 'Suppliers and quality'), t('شراء بن محمّص ومخبوزات، مع وصفات وأوزان وتسجيل هدر ومورد بديل.', 'Purchase roasted beans and bakery items, with standard recipes, weights, waste records and a backup supplier.'), t('عينات وعروض أسعار وشروط دفع وتوريد وصلاحية؛ اختبار ثبات المنتج والتخزين.', 'Obtain samples, quotations, payment and delivery terms and shelf-life details; test product consistency and storage.')],
          [t('الأنظمة والتراخيص', 'Systems and licences'), t('نظام بيع وتقارير يومية ومتابعة مخزون وتحقق من متطلبات النشاط والموقع.', 'Point of sale, daily reports, stock tracking and confirmation of activity and site requirements.'), t('تأكيد المتطلبات والرسوم السارية لدى الجهات المختصة قبل توقيع عقد ملزم؛ بند 8,000 للتجهيز المسبق ليس تسعيرة رسوم حكومية.', 'Confirm current requirements and fees with the relevant authorities before a binding commitment. The SAR 8,000 pre-opening line is not an official fee schedule.')],
        ]} />
      </section>

      <section id="assumptions" className={styles.section}><span className={styles.sectionNumber}>05</span><h2>{t('كل رقم له حالة واضحة.', 'Every figure has a clear status.')}</h2>
        <DataTable caption={t('سجل السيناريو الأساسي · 6 سبتمبر 2026', 'Base-case register · 6 September 2026')} headers={[t('المدخل', 'Input'), t('الافتراض الأساسي', 'Base assumption'), t('المصدر والحالة', 'Source and status')]} rows={[
          [t('الفواتير اليومية', 'Daily transactions'), '90', t('افتراض تعليمي؛ يحتاج إثباتًا بمبيعات مدفوعة وتكرار شراء.', 'Illustrative assumption; needs paid-sales and repeat-purchase evidence.')],
          [t('متوسط الفاتورة', 'Average transaction'), t('28 ر.س شامل الضريبة', 'SAR 28 including VAT'), t('افتراض تعليمي؛ يحتاج سلة منتجات ومزيج مبيعات مقاسًا.', 'Illustrative assumption; needs a measured basket and sales mix.')],
          [t('أيام التشغيل', 'Operating days'), t('30 يومًا لكل شهر نموذجي', '30 days per model month'), t('تبسيط حسابي؛ لا يمثل تقويمًا فعليًا أو موسمية رمضان والإجازات.', 'Modelling convention; not a calendar forecast or Ramadan/holiday seasonality.')],
          [t('التكلفة المتغيرة', 'Variable cost'), t('35% من الإيراد دون الضريبة', '35% of revenue excluding VAT'), t('افتراض تعليمي يشمل المواد والتغليف والهدر ورسوم الدفع؛ يحتاج تكلفة وصفات وعروض موردين.', 'Illustrative ingredients, packaging, waste and payment-fee allowance; needs recipe costs and supplier quotations.')],
          [t('التكاليف الثابتة والتجهيز', 'Fixed costs and setup'), t('38,000 شهريًا / 231,000 قبل الافتتاح', '38,000 monthly / 231,000 before opening'), t('افتراضات تعليمية مفصلة أدناه؛ ليست أسعارًا محلية متحققًا منها.', 'Illustrative budgets detailed below; not verified local prices.')],
          [t('الوديعة والمخزون', 'Deposit and stock'), t('29,000 ر.س', 'SAR 29,000'), t('21,000 وديعة إيجار مستقلة عن الإيجار الشهري، و8,000 مخزون افتتاحي؛ افتراضان يحتاجان شروطًا فعلية.', '21,000 rent deposit separate from monthly rent, plus 8,000 opening stock; both require actual terms.')],
          [t('الاحتياطي والتدرّج', 'Reserve and ramp-up'), t('3 أشهر تكلفة ثابتة / استقرار من الشهر السابع', '3 months of fixed costs / steady state from month seven'), t('اختيار تخطيطي لا معيار ملاءمة؛ يُختبر مقابل أكبر عجز تراكمي وسيناريو الطلب الضعيف.', 'Planning choices, not adequacy benchmarks; test against peak cumulative deficit and weak demand.')],
          [t('ضريبة القيمة المضافة', 'Value added tax'), '15%', <>{t('معدل الضريبة الأساسي حسب ', 'Standard rate per ')}<a href="https://zatca.gov.sa/en/MediaCenter/News/Pages/News-342.aspx">{t('هيئة الزكاة والضريبة والجمارك', 'ZATCA')}</a>{t('؛ يفترض المثال نشاطًا مسجلًا من الافتتاح.', '; the example assumes a registered business from launch.')}</>],
        ]} />
      </section>

      <section id="budget" className={styles.section}><span className={styles.sectionNumber}>06</span><h2>{t('من أين يأتي احتياج التمويل؟', 'What creates the funding requirement?')}</h2>
        <p>{t('الجداول التالية توثّق الافتراض الأساسي بالريال السعودي، قبل ضريبة المدخلات القابلة للاسترداد. بند التجهيز يجمع أصولًا ومصاريف ما قبل الافتتاح؛ لا يُعامل كله كأصل قابل للإهلاك. لا تُعدّل هذه الجداول عند تخصيص الحاسبة.', 'These tables document the base assumptions in SAR, excluding recoverable input VAT. Setup includes both assets and pre-opening expenses; it is not all treated as depreciable capital. These tables remain the base reference when the calculator is customised.')}</p>
        <DataTable caption={t('التجهيز ومصاريف ما قبل الافتتاح — ر.س', 'Setup and pre-opening expenditure — SAR')} headers={[t('البند', 'Item'), t('الميزانية المفترضة', 'Assumed budget')]} rows={[
          ...SETUP_COSTS.map(row => [row[locale], amount(row.amount)]),
          [t('الإجمالي', 'Total'), amount(BASE_INPUTS.setupCost)],
        ]} />
        <DataTable caption={t('تكاليف التشغيل الثابتة شهريًا — ر.س', 'Monthly fixed operating costs — SAR')} headers={[t('البند', 'Item'), t('الميزانية المفترضة', 'Assumed budget')]} rows={[
          ...FIXED_COSTS.map(row => [row[locale], amount(row.amount)]),
          [t('الإجمالي', 'Total'), amount(BASE_INPUTS.fixedMonthlyCost)],
        ]} />
        <DataTable compactDetails caption={t('ملخص التمويل الأولي الأساسي — ر.س', 'Base initial funding summary — SAR')} headers={[t('الاستخدام', 'Use'), t('المبلغ', 'Amount'), t('التفسير', 'Explanation')]} rows={[
          [t('تجهيز ومصاريف ما قبل الافتتاح', 'Setup and pre-opening'), amount(BASE_INPUTS.setupCost), t('يتضمن احتياطي تجاوز تكلفة التجهيز 21,000؛ لا يتكرر ضمن مصاريف التشغيل.', 'Includes a 21,000 setup contingency; it is not repeated as an operating cost.')],
          [t('وديعة إيجار ومخزون افتتاحي', 'Rent deposit and opening stock'), amount(BASE_INPUTS.depositAndStock), t('تجميد نقد 21,000 + مخزون 8,000. يُفترض ثبات المخزون لاحقًا، وتجديد المستهلك ضمن التكلفة المتغيرة.', '21,000 tied up as a deposit + 8,000 inventory. Stock remains constant afterwards; replenishment of consumption is included in variable cost.')],
          [t('نقد متاح بعد الافتتاح', 'Cash available after opening'), amount(base.reserve), t('38,000 × 3 أشهر. الاحتياطي رصيد نقدي وليس مصروفًا إضافيًا.', '38,000 × 3 months. The reserve is cash, not an additional expense.')],
          [t('إجمالي التمويل داخل النطاق', 'Total funding within scope'), amount(base.funding), t('لا يتضمن تمويل توقيت الضريبة أو خدمة دين أو توسعًا لاحقًا؛ تُضاف عند تحديدها.', 'Excludes VAT timing finance, debt service and later expansion; add them when defined.')],
        ]} />
      </section>

      <section id="financial-model" className={styles.section}><span className={styles.sectionNumber}>07</span><h2>{t('اختبر المبيعات والتكلفة والسيولة معًا.', 'Test sales, costs and cash together.')}</h2>
        <p>{t('السيناريوهات احتمالات تعليمية بلا أوزان احتمالية، ولا تمثل توقعات سوق. يزيد السيناريو المتفائل ميزانية التكلفة الثابتة لاستيعاب تشغيل أعلى؛ والمتحفّظ يجمع طلبًا أقل وتكلفة أكبر.', 'The scenarios are illustrative possibilities without probability weights, not market forecasts. The optimistic case includes a higher fixed-cost budget for increased operations; the conservative case combines weaker demand with higher costs.')}</p>
        <DataTable caption={t('مقارنة السيناريوهات الجاهزة — لا تتغير مع المدخلات المخصصة', 'Preset scenario comparison — unchanged by custom inputs')} headers={[t('السيناريو', 'Scenario'), t('فواتير / يوم', 'Transactions / day'), t('متوسط الفاتورة شامل الضريبة', 'Average transaction including VAT'), t('تكلفة متغيرة', 'Variable cost'), t('تكلفة ثابتة شهرية', 'Monthly fixed cost'), t('فائض التشغيل السنوي الأول', 'First-year operating surplus')]} rows={SCENARIOS.map(item => [item[locale], amount(item.inputs.dailyOrders), amount(item.inputs.averageTicket), `${item.inputs.variableCostPct}%`, amount(item.inputs.fixedMonthlyCost), amount(calculateFeasibility(item.inputs).yearOperatingSurplus)])} />
        <p className={styles.small}>{t('جميع القيم المالية في المقارنة بالريال. السيناريوهات تستخدم 30 يومًا شهريًا، وتجهيزًا 231,000، ووديعة ومخزونًا 29,000، واحتياطيًا يساوي ثلاثة أشهر من تكلفتها الثابتة.', 'Financial values are in SAR. Presets use 30 days per month, 231,000 in setup, 29,000 in deposit and stock, and a reserve equal to three months of their respective fixed costs.')}</p>
        <FeasibilityCalculator locale={locale} />
        <p>{t('فحص الحساسية: خفّض الفواتير وحدها، ثم ارفع تكلفة المواد وحدها، ثم جرّب التغيرين معًا. راقب التعادل وأقل رصيد نقدي، لا إجمالي المبيعات فقط. النموذج لا يحسب قيمة حالية أو عائدًا داخليًا أو استرداد استثمار؛ هذه تحتاج أفقًا أطول وتفاصيل الضرائب والتمويل والإحلال وقيمة نهاية المشروع.', 'Sensitivity check: reduce transactions alone, then raise variable costs alone, then combine both changes. Watch break-even and the lowest cash balance as well as sales. NPV, IRR and investment payback are not calculated; they require a longer horizon and defined tax, financing, replacement and terminal-value assumptions.')}</p>
      </section>

      <section id="risks" className={styles.section}><span className={styles.sectionNumber}>08</span><h2>{t('متى نمضي، ومتى نعيد النظر؟', 'When would we proceed or revise?')}</h2>
        <DataTable caption={t('سجل مخاطر أولي وقرارات مرتبطة به', 'Initial risk register and associated decisions')} headers={[t('الخطر', 'Risk'), t('إشارة نراقبها', 'Signal to watch'), t('الاستجابة المقترحة', 'Proposed response')]} rows={[
          [t('طلب أقل من التعادل', 'Demand below break-even'), t('الفواتير المدفوعة لا تدعم حد التعادل خلال فترة اختبار متفق عليها.', 'Paid transactions fail to support break-even over an agreed test period.'), t('مراجعة الموقع والعرض وحجم الفرع قبل زيادة الإنفاق؛ لا تعالج الفجوة بحملة هوية وحدها.', 'Review location, offer and branch size before increasing spend; branding alone cannot close the gap.')],
          [t('تآكل هامش المساهمة', 'Contribution erosion'), t('تكلفة الوصفات والهدر أعلى من النسبة المفترضة أو تغيّر مزيج المنتجات.', 'Recipe costs or waste exceed the assumed ratio, or product mix changes.'), t('إعادة حساب تكلفة الصنف والسلة، وضبط الحصص والمورد والسعر، ثم تحديث التعادل.', 'Recalculate item and basket costs, adjust portions, suppliers and prices, then update break-even.')],
          [t('ضغط سيولة التأسيس', 'Startup cash pressure'), t('دفعات إيجار أو تجهيز مقدمة، تأخير افتتاح، أو رصيد تشغيلي سالب.', 'Upfront rent or fit-out payments, opening delays or negative operating cash.'), t('جدول دفعات فعلي وجدول ضريبة مستقل؛ اختبار احتياطي إضافي وتأجيل البنود غير الضرورية.', 'Use actual payment terms and a separate VAT schedule; test extra reserves and defer nonessential spending.')],
          [t('ازدحام وتفاوت جودة', 'Queues and inconsistent quality'), t('ارتفاع زمن الخدمة أو الشكاوى في الذروة رغم كفاية المتوسط اليومي.', 'Peak waiting times or complaints rise despite manageable daily averages.'), t('اختبار تخطيط المحطات والورديات وتبسيط القائمة؛ احتساب تكلفة زيادة الطاقة.', 'Test station layout and shifts, simplify the menu and cost any capacity increase.')],
          [t('متطلبات موقع أو نشاط غير محسومة', 'Unresolved site or activity requirements'), t('غياب تأكيد ملاءمة الموقع أو الاشتراطات والرسوم.', 'Site suitability, conditions or fees remain unconfirmed.'), t('حسم المتطلبات مع الجهات المختصة والمختصين قبل عقد ملزم أو تجهيز.', 'Resolve requirements with the relevant authorities and specialists before a binding lease or fit-out.')],
        ]} />
        <div className={styles.grid}>
          <article className={styles.card}><h3>{t('شروط المضي المقترحة', 'Proposed conditions to proceed')}</h3><ul><li>{t('طلب مدفوع قابل للتكرار يدعم التعادل مع هامش احتياط يتفق عليه المالك.', 'Repeatable paid demand supports break-even plus a buffer agreed with the owner.')}</li><li>{t('عروض إيجار وتجهيز وتوريد مكتوبة، وخطة فريق وطاقة قابلة للتنفيذ.', 'Written rent, fit-out and supplier quotations, with a workable staffing and capacity plan.')}</li><li>{t('سيولة تغطي مسار التدرّج والسيناريو الضعيف ضمن حد خسارة مقبول، بعد إضافة الضريبة والتمويل الفعليين.', 'Cash covers ramp-up and the weak case within an accepted loss limit, after actual VAT timing and financing are added.')}</li></ul></article>
          <article className={styles.card}><h3>{t('خطة التحقق قبل الاستثمار', 'Validation before investment')}</h3><p>{t('أولًا: توثيق المواقع والعملاء والبدائل. ثانيًا: عروض الأسعار وتكلفة الوصفات والورديات. ثالثًا: اختبار بيع محدود وقياس الخدمة والعودة. رابعًا: استبدال الافتراضات بالأدلة، وإعادة حساب السيناريوهات ثم اعتماد القرار. لا تُحدد مدة أو نتيجة مضمونة قبل اختيار الموقع ونطاق الاختبار.', 'First document sites, customers and alternatives. Then obtain quotations and cost recipes and shifts. Run a limited paid sales and service test, including repeat visits. Replace assumptions with evidence, recalculate scenarios and make the decision. Timing and outcomes cannot be fixed before the site and test scope are defined.')}</p></article>
        </div>
      </section>

      <section id="brand" className={styles.section}><span className={styles.sectionNumber}>09</span><h2>{t('كيف تنتقل الجدوى إلى استراتيجية الهوية؟', 'How does feasibility inform the identity strategy?')}</h2>
        <p>{t('الربط التالي مقترح لسُمرة، ويظل مشروطًا بتحقق فرضيات الدراسة. ما تثبته الأرقام وتجربة العميل يحدد الوعد الذي تستطيع العلامة الوفاء به، ثم تُصمم تطبيقاتها على هذا الأساس.', 'The following connections are proposals for SUMRA, conditional on validating the study’s hypotheses. Financial evidence and customer experience define a promise the business can deliver, which then guides its applications.')}</p>
        <DataTable caption={t('من فرضية تجارية إلى قرار علامة وتطبيق بصري', 'From commercial hypothesis to brand decision and visual application')} headers={[t('نتيجة نريد التحقق منها', 'Finding to validate'), t('قرار استراتيجي مقترح', 'Proposed strategic decision'), t('تطبيق في الهوية والتجربة', 'Identity and experience application')]} rows={[
          [t('زيارة يومية متكررة', 'Recurring everyday visits'), t('قهوة موثوقة وقريبة من الروتين، بخدمة يمكن الحفاظ على سرعتها.', 'Dependable everyday coffee with consistently deliverable service.'), t('قائمة سهلة القراءة، مسار استلام واضح، ورسائل قصيرة على الكوب واللوحات.', 'Readable menus, clear pickup navigation and concise cup and signage copy.')],
          [t('الحاجة لفهم التحميص', 'Need to understand roast levels'), t('تسهيل الاختيار بدل المبالغة في لغة الخبراء.', 'Make selection approachable without overloading customers with jargon.'), t('درجات سُمرة البنية تقترن بأسماء ونصوص واضحة على أكياس البن؛ لا نعتمد اللون وحده لنقل المعلومة.', 'Pair SUMRA’s brown roast palette with clear names and text on coffee bags; colour is never the only information cue.')],
          [t('هامش مساهمة يحتاج ضبطًا', 'Contribution needs discipline'), t('قيمة مدركة من ثبات المنتج ووضوحه، مع تغليف يناسب اقتصاد الصنف.', 'Perceived value through consistency and clarity, with packaging that fits item economics.'), t('تحديد مقاسات ومواد طباعة محدودة، وتسعير تكلفة الكيس والكوب قبل توسيع التطبيقات.', 'Limit print formats and materials, and cost bags and cups before expanding the application system.')],
          [t('التدرّج يستهلك النقد', 'Ramp-up consumes cash'), t('إطلاق مرحلي بأولويات تخدم البيع والتشغيل.', 'A phased launch prioritising sales and operations.'), t('ابدأ بالواجهة والقائمة والتغليف الأساسي وحضور رقمي واضح؛ تُؤجل التطبيقات الثانوية حتى يثبت الطلب.', 'Start with storefront, menu, essential packaging and a clear digital presence; defer secondary applications until demand is established.')],
          [t('شراء بن للمنزل قابل للتكرار', 'Repeatable home-coffee purchases'), t('قصة تتبع المنتج وتشرح الاختيار دون ادعاءات غير مثبتة.', 'Product storytelling that explains choices without unsupported claims.'), t('بطاقة كيس واضحة للمنتج والتحميص والطحنة وطريقة التحضير وفق المعلومات الفعلية للمورد.', 'Clear pack information for product, roast, grind and brewing, based on actual supplier information.')],
        ]} />
        <div className={styles.actions}><Link className={styles.button} href={`/${locale}/work/sumra`}>{t('تابع إلى استراتيجية سُمرة وهويتها كاملة', 'Continue to SUMRA’s full strategy and identity')}</Link><Link className={styles.button} href={`/${locale}/services/feasibility`}>{t('تعرّف على خدمة دراسة الجدوى', 'Explore the feasibility service')}</Link></div>
      </section>

      <section id="sources" className={styles.section}><span className={styles.sectionNumber}>10</span><h2>{t('المصادر وحدود القراءة والتحديث.', 'Sources, boundaries and updates.')}</h2>
        <ol className={styles.sources}>
          <li><a href="https://zatca.gov.sa/en/MediaCenter/News/Pages/News-342.aspx">{t('هيئة الزكاة والضريبة والجمارك — تطبيق ضريبة القيمة المضافة بنسبة 15%', 'ZATCA — 15% VAT implementation')}</a><p>{t('خبر منشور في 30 يونيو 2020 عن سريان المعدل في 1 يوليو 2020. استُخدم لتوثيق معدل ضريبة المبيعات في المثال. لا يثبت حالة تسجيل مشروع بعينه أو تكلفة أو طلبًا تجاريًا.', 'Published 30 June 2020, announcing the rate effective 1 July 2020. Used here to document the model’s sales VAT rate. It does not establish any specific business’s registration status, commercial costs or demand.')}</p></li>
          <li><a href="https://www.sba.gov/counseling/plan-your-business/">{t('إدارة الأعمال الصغيرة الأمريكية — تخطيط المشروع وحساب تكاليف البداية والتعادل', 'U.S. Small Business Administration — business planning, startup costs and break-even')}</a><p>{t('مرجع منهجي لفصل مصاريف البداية عن المصاريف الشهرية، وحساب التعادل من التكلفة الثابتة ومساهمة الوحدة. نطبّق المنطق على متوسط فاتورة مركّب؛ المرجع ليس مصدر أسعار أو بيانات سوق سعودية.', 'A methodology reference for separating startup and monthly costs and calculating break-even from fixed costs and unit contribution. Here the unit is a blended average transaction. This reference does not provide Saudi prices or market data.')}</p></li>
        </ol>
        <p>{t('تاريخ الاطلاع وإعداد هذا المثال: 6 سبتمبر 2026. جميع أرقام السوق والتشغيل غير المنسوبة صراحة إلى مرجع هي افتراضات تعليمية من أثر. لا يوجد ادعاء بزيارات ميدانية أو مقابلات أو تعاقدات أو نتائج تشغيل.', 'References reviewed and example prepared on 6 September 2026. All market and operating figures not explicitly attributed to a reference are illustrative ATHR assumptions. No field visits, interviews, contracts or operating results are claimed.')}</p>
        <p>{t('يُحدّث النموذج عند ورود عرض سعر أو اختيار موقع أو تغيير قائمة أو قياس طلب، مع تسجيل تاريخ كل مدخل ومصدره ومسؤوله. ولتحويله إلى دراسة قرار فعلية، تضاف الموسمية وشروط الدفع والضريبة والإهلاك والتمويل والإحلال وأفق التوقعات المناسب.', 'Update the model when quotations arrive, a site is selected, the menu changes or demand is measured, recording each input’s date, source and owner. For an actual decision study, add seasonality, payment terms, VAT timing, depreciation, financing, replacement and an appropriate forecast horizon.')}</p>
      </section>
    </div>
  </FeasibilityFrame>;
}
