import Link from 'next/link';
import { Seal } from '@/components/brand/Seal';
import styles from './wizan.module.css';
type Props={params:{locale:'ar'|'en'}};
function Mark({className=''}:{className?:string}){return <svg className={className} viewBox="0 0 512 512" role="img" aria-label="WIZAN"><path d="M184.15 410.07A170 170 0 1 1 327.85 410.07" fill="none" stroke="currentColor" strokeWidth="34" strokeLinecap="round"/><path d="M208.67 357.51A112 112 0 0 1 208.67 154.49" fill="none" stroke="#91A79D" strokeWidth="34" strokeLinecap="round"/><path d="M303.33 154.49A112 112 0 0 1 208.67 357.51" fill="none" stroke="#DD776A" strokeWidth="34" strokeLinecap="round"/><circle cx="256" cy="256" r="26" fill="currentColor"/><circle cx="365" cy="118" r="14" fill="#6087A0"/></svg>}
export default function WizanCase({params}:Props){const ar=params.locale==='ar';return <main className={styles.page} dir={ar?'rtl':'ltr'}>
<header className={styles.nav}><Link href={`/${params.locale}`} className={styles.brand}><Seal variant="full" idSuffix="wizan-case" className={styles.seal}/><span>ATHR BRANDS</span></Link><Link href={`/${params.locale}#work`} className={styles.back}>{ar?'العودة إلى الأعمال':'Back to work'}</Link></header>
<section className={styles.hero}><div className={styles.heroCopy}><p>{ar?'مشروع تصوري مستقل من ATHR BRANDS':'Independent concept project by ATHR BRANDS'}</p><h1>{ar?'وِزان':'WIZAN'}<small>WIZAN</small></h1><h2>{ar?'عافية تُقاس. حياة تتوازن.':'Measure wellbeing. Live in balance.'}</h2><div className={styles.meta}>{ar?'استراتيجية · تسمية · هوية لفظية وبصرية · نظام رقمي':'Strategy · Naming · Verbal & Visual Identity · Digital System'}</div></div><Mark className={styles.heroMark}/></section>
<section className={styles.intro}><span>01</span><div><p>{ar?'الفرصة':'The opportunity'}</p><h2>{ar?'المشكلة ليست غياب المعرفة، بل غياب نظام يضعها في سياق يمكن تطبيقه.':'The problem is not lack of knowledge, but lack of a system that makes it actionable.'}</h2><p>{ar?'القياس صار متاحًا عبر الساعات والتطبيقات، لكن المعنى ما زال متفرقًا. الفرصة ليست في إضافة تطبيق قياس جديد، بل في سد المسافة بين الرقم والقرار.':'Measurement is abundant through watches and apps, but meaning remains fragmented. The opportunity is not another tracking app; it is closing the gap between the number and the decision.'}</p></div></section>
<section className={styles.dark}><div className={styles.sectionHead}><span>02</span><p>{ar?'التحدي':'The challenge'}</p><h2>{ar?'بيانات كثيرة، قرار قليل.':'More data. Less decision.'}</h2><p>{ar?'تشتت المؤشرات، لغة تقنية مربكة، وصفات موحدة لا تراعي السياق، ثم اندفاع قصير ينتهي بانقطاع الالتزام. النتيجة السلوكية التي ترفضها العلامة: شعور بالذنب بدل شعور بالتقدم.':'Fragmented indicators, technical language, one-size-fits-all plans and short bursts of motivation that end in drop-off. The behavior the brand refuses to create is guilt instead of progress.'}</p></div><Mark className={styles.bigMark}/><div className={styles.principles}><article><b>01</b><span>{ar?'تشتت المؤشرات':'Fragmented indicators'}</span></article><article><b>02</b><span>{ar?'لغة مربكة':'Confusing language'}</span></article><article><b>03</b><span>{ar?'وصفات موحدة':'Generic prescriptions'}</span></article></div></section>
<section className={styles.intro}><span>03</span><div><p>{ar?'التموضع':'Positioning'}</p><h2>{ar?'تفسير إنساني مبني على سياق شخصي.':'Human interpretation grounded in personal context.'}</h2><p>{ar?'المساحة التي تختارها وِزان تقع بين الرقم الخام والنصيحة العامة: تفسّر ولا تشخّص، وتقترح ولا تصف علاجًا. التموضع هنا التزام بحدود واضحة، لا ادعاء تفرد مطلق.':'WIZAN sits between raw numbers and generic advice: it interprets without diagnosing, and suggests without prescribing treatment. The positioning is a commitment to clear boundaries, not a claim of absolute uniqueness.'}</p></div></section>
<section className={styles.dark}><div className={styles.sectionHead}><span>04</span><p>{ar?'مبادئ القرار':'Decision principles'}</p><h2>{ar?'قواعد تُختبر قبل أن تتحول إلى تصميم.':'Rules tested before they become design.'}</h2></div><div className={styles.principles}><article><b>{ar?'الوضوح قبل الاكتمال':'Clarity before completeness'}</b><span>{ar?'هل تُفهم الشاشة خلال خمس ثوانٍ؟':'Can the screen be understood in five seconds?'}</span></article><article><b>{ar?'السياق قبل الوصفة':'Context before prescription'}</b><span>{ar?'هل تتغير التوصية إذا تغير سياق المستخدم؟':'Does the recommendation change when context changes?'}</span></article><article><b>{ar?'الاستمرار قبل المثالية':'Consistency before perfection'}</b><span>{ar?'هل يمكن تنفيذ الخطوة في يوم سيئ؟':'Can the step still be done on a bad day?'}</span></article></div></section>
<section className={styles.identity}><div className={styles.sectionHead}><span>05</span><p>{ar?'الفكرة المنظمة':'Organizing idea'}</p><h2>{ar?'الاتزان في حركة.':'Balance in motion.'}</h2><p>{ar?'الاتزان ليس رقمًا يُبلغ مرة واحدة، بل إيقاع يومي يمكن قراءته وتحسينه.':'Balance is not a number reached once, but a daily rhythm that can be read and improved.'}</p></div><div className={styles.anatomy}><Mark/><div><p>{ar?'المسارات الدائرية غير المكتملة تمثل أبعاد العافية المتغيرة. المركز ثابت لأن الإنسان هو المرجع، والنقطة الحرة تشير إلى الخطوة التالية.':'Open circular paths represent changing dimensions of wellbeing. The center stays fixed because the person is the reference; the free point signals the next step.'}</p><strong>{ar?'الدائرة المغلقة رُفضت لأنها تدّعي الاكتمال، بينما الوعد مبني على التدرج لا الكمال.':'A closed circle was rejected because it suggests completion, while the promise is built on progression rather than perfection.'}</strong></div></div><div className={styles.palette}><i/><i/><i/><i/><i/></div></section>
<section className={styles.dark}><div className={styles.sectionHead}><span>06</span><p>{ar?'نظام الشعار':'Logo system'}</p><h2>{ar?'من أيقونة التطبيق إلى العرض المؤسسي.':'From app icon to institutional presentation.'}</h2><p>{ar?'النظام يتضمن نسخة أفقية أساسية، نسخة رأسية، ورمزًا مستقلاً. في الاستخدام ثنائي اللغة تأتي العربية أولًا وأعلى دائمًا، واللاتينية تحتها بحجم لا يتجاوز 40٪ من ارتفاع الاسم العربي.':'The system includes a primary horizontal lockup, a vertical version and a standalone symbol. In bilingual use, Arabic comes first and above, with Latin below at no more than 40% of the Arabic name height.'}</p></div><Mark className={styles.bigMark}/><div className={styles.principles}><article><b>{ar?'المساحة الآمنة':'Clear space'}</b><span>{ar?'تُحسب من الحد الخارجي للمسار لا من ملف التصدير.':'Measured from the outer path, not the export bounds.'}</span></article><article><b>{ar?'الحجم الأدنى':'Minimum size'}</b><span>{ar?'نسخ مبسطة عند الأحجام الصغيرة لحماية الوضوح.':'Simplified versions protect clarity at small sizes.'}</span></article><article><b>{ar?'النسخة الأحادية':'Monochrome'}</b><span>{ar?'الفكرة تبقى في الشكل حتى دون اللون.':'The idea remains in the form even without color.'}</span></article></div></section>
<section className={styles.product}><div className={styles.sectionHead}><span>07</span><p>{ar?'التطبيق الرقمي':'Digital product'}</p><h2>{ar?'القرار أهم من القراءة.':'The decision matters more than the reading.'}</h2></div><div className={styles.phone}><div className={styles.phoneTop}><Mark/><b>WIZAN</b></div><small>{ar?'صباح الخير، نورة':'Good morning, Noura'}</small><strong>78</strong><em>{ar?'مؤشر العافية اليوم':'Today’s wellbeing indicator'}</em><div className={styles.bars}><i/><i/><i/><i/><i/></div><button>{ar?'عرض خطة اليوم':'View today’s plan'}</button></div><div className={styles.report}><b>{ar?'تقرير العافية':'WELLBEING REPORT'}</b><span>WEEK 24</span><h3>{ar?'صورة أسبوعية تساعدك على اختيار الأولوية التالية.':'A weekly view that helps you choose the next priority.'}</h3><div><i/><i/><i/></div></div></section>
<section className={styles.intro}><span>08</span><div><p>{ar?'قواعد الكتابة':'Writing rules'}</p><h2>{ar?'لغة قصيرة، دقيقة، ولا تُشعر المستخدم بالذنب.':'Short, precise language that never shames the user.'}</h2><p>{ar?'في الواجهة لا تتجاوز الجملة 14 كلمة، وفي التقرير 22 كلمة. تخاطب وِزان المستخدم بصيغة محايدة قدر الإمكان، وتشرح المصطلح الطبي عند ظهوره أول مرة، وتستخدم الأرقام الغربية لسهولة القراءة داخل الرسوم والجداول.':'Interface sentences stay within 14 words and report sentences within 22. WIZAN uses neutral address where possible, explains medical terms at first use and uses Western Arabic numerals for consistency in charts and tables.'}</p></div></section>
<section className={styles.close}><p>{ar?'هذا المشروع تصوري وليس عملًا منفذًا لعميل حقيقي. لم تُجرَ له دراسة سوق ميدانية، وأي إطلاق فعلي يستوجب بحثًا كميًا وفحصًا قانونيًا وتنظيميًا واعتمادًا للادعاءات الصحية.':'This is a concept project, not commissioned client work. No field market study was conducted; any real launch would require quantitative research, legal and regulatory review, and approval of health claims.'}</p><Link href={`/${params.locale}#work`}>{ar?'العودة إلى الأعمال':'Back to selected work'}</Link></section>
</main>}
