import Link from 'next/link';
import { Seal } from '@/components/brand/Seal';
import styles from './athr.module.css';

type Props={params:{locale:'ar'|'en'}};
export default function AthrCase({params}:Props){const ar=params.locale==='ar';return <main className={styles.page} dir={ar?'rtl':'ltr'}>
<header className={styles.nav}><Link href={`/${params.locale}`} className={styles.brand}><Seal variant="full" idSuffix="athr-v2-nav" className={styles.seal}/><span>ATHR BRANDS</span></Link><Link href={`/${params.locale}#work`} className={styles.back}>{ar?'العودة إلى الأعمال':'Back to work'}</Link></header>
<section className={styles.hero}><div><p>BRAND STRATEGY &amp; IDENTITY · V2.0</p><h1>{ar?'هويةٌ تُرى.':'An identity seen.'}<br/><em>{ar?'أثرٌ يبقى.':'An impact that remains.'}</em></h1><p className={styles.lede}>{ar?'نظام بصري واضح، ورسالة متماسكة، وتجربة تليق بطموح العلامة.':'A clear visual system, a coherent message, and an experience worthy of the brand’s ambition.'}</p></div><Seal variant="full" idSuffix="athr-v2-hero" className={styles.heroSeal}/></section>
<section className={styles.statement}><span>01</span><div><p>{ar?'التموضع':'Positioning'}</p><h2>{ar?'استوديو متخصص يبني أنظمة هوية واضحة للعلامات الطموحة.':'A specialist studio building clear identity systems for ambitious brands.'}</h2><p>{ar?'لأصحاب المشاريع والعلامات التي تريد حضورًا واضحًا وراقيًا، تقدّم «أثر» نظام هوية يجمع بين الفهم الاستراتيجي والتنفيذ البصري الدقيق؛ ليمنح العلامة وضوحًا واتساقًا وقابلية للنمو.':'For ambitious brands seeking a clear, refined presence, ATHR combines strategic understanding with precise visual execution to create clarity, consistency and room to grow.'}</p></div></section>
<section className={styles.dark}><div className={styles.head}><span>02</span><p>{ar?'ما الذي يميز المنهج؟':'What defines the approach?'}</p><h2>{ar?'نشرح لماذا اخترنا، لا ماذا رسمنا فقط.':'We explain why we chose—not only what we drew.'}</h2></div><div className={styles.grid}><article><b>{ar?'نظام لا شعار منفرد':'A system, not a lone logo'}</b><p>{ar?'نربط كل عنصر بقواعد تضمن ثبات التجربة عبر كل نقطة تواصل.':'Every element is governed by rules that keep the experience consistent.'}</p></article><article><b>{ar?'فهم محلي بلغة عالمية':'Local understanding, global language'}</b><p>{ar?'نقرأ السياق العربي والسعودي، ونصوغه بصريًا بمعايير معاصرة.':'We read Saudi and Arabic context, then express it through contemporary standards.'}</p></article><article><b>{ar?'تطبيق واقعي':'Built for real use'}</b><p>{ar?'نسلّم أدوات يستطيع العميل استخدامها بعد انتهاء المشروع.':'We deliver tools the client can actually use after the project ends.'}</p></article><article><b>{ar?'تبرير القرارات':'Reasoned decisions'}</b><p>{ar?'كل قرار بصري يعود إلى سبب واضح داخل النظام.':'Every visual decision traces back to a clear reason in the system.'}</p></article></div></section>
<section className={styles.voice}><div className={styles.head}><span>03</span><p>{ar?'نبرة الصوت':'Voice'}</p><h2>{ar?'واضح، هادئ، وواثق.':'Clear, calm and confident.'}</h2></div><div className={styles.do}><article><small>{ar?'نفعل':'WE DO'}</small><p>{ar?'نكتب بجُمل مباشرة وقصيرة. نشرح الفكرة قبل المصطلح. نتحدث عن النتيجة لا عن الأدوات، ونعترف بالحدود بوضوح.':'We write directly, explain the idea before the terminology, focus on outcomes rather than tools, and state limits clearly.'}</p></article><article><small>{ar?'نتجنب':'WE AVOID'}</small><p>{ar?'المبالغة والادعاءات المطلقة، والمصطلحات المعقدة بلا داعٍ، والضغط البيعي، والعبارات العامة المكررة.':'Exaggeration, absolute claims, needless jargon, sales pressure and generic repeated phrases.'}</p></article></div><blockquote>{ar?'«نبني نظامًا بصريًا يساعد علامتك على الظهور بوضوح واتساق.»':'“We build a visual system that helps your brand appear with clarity and consistency.”'}</blockquote></section>
<section className={styles.system}><div className={styles.head}><span>04</span><p>{ar?'النظام':'The system'}</p><h2>{ar?'مرجع واحد يحكم التنفيذ.':'One reference governs execution.'}</h2></div><div className={styles.systemGrid}><div className={styles.logoPanel}><Seal variant="full" idSuffix="athr-v2-system"/><strong>ATHR BRANDS</strong><small>{ar?'أثر لصناعة الهويات البصرية':'Brand identity studio'}</small></div><div className={styles.rules}><p>{ar?'عند تعارض أي مادة منشورة مع وثيقة الهوية، تُعدّل المادة لا الوثيقة. ويُرفع رقم الإصدار عند تغيير الشعار أو الألوان أو الخطوط أو بيان التموضع.':'When published material conflicts with the identity document, the material changes—not the document. Versioning is updated when the logo, colors, typography or positioning changes.'}</p><div className={styles.palette}><i/><i/><i/></div></div></div></section>
<section className={styles.close}><h2>{ar?'هويةٌ تُرى. أثرٌ يبقى.':'An identity seen. An impact that remains.'}</h2><p>{ar?'هذه الصفحة مبنية على دراسة ATHR BRANDS المعتمدة — الإصدار 2.0، سبتمبر 2026.':'This page is based on the approved ATHR BRANDS identity study — version 2.0, September 2026.'}</p><Link href={`/${params.locale}#work`}>{ar?'العودة إلى الأعمال':'Back to selected work'}</Link></section>
</main>}
