import financial from '../aevu-financial.json';
import { bilingual as L, type BudgetRow, type ModelConfig } from '@/lib/portfolio-feasibility-model';
import type { PortfolioFeasibilityStudy, StudyCard } from './types';

const C = (ar: string, en: string, bodyAr: string, bodyEn: string): StudyCard => ({ title: L(ar, en), body: L(bodyAr, bodyEn) });
const A = financial.assumptions;
const budget = (rows: (string | number)[][], labels: string[]): BudgetRow[] => rows.map(([label, amount], i) => ({ label: L(String(label), labels[i]), amount: Number(amount) }));
const setup = budget(financial.setup, ['Fragrance development and samples', 'Identity, store and photography', 'Packaging and print samples', 'One trademark request in one class', 'Quality and compatibility tests', 'Contracts and notification preparation', 'Pre-launch test', 'Setup contingency']);
const fixed = budget(financial.fixed, ['Working founder allowance', 'Part-time customer service', 'Basic storage', 'Ongoing content', 'Platform and systems', 'Accounting and administration', 'Quality and insurance allowance', 'Support costs']);
const base = { volume: 450, price: financial.unitEconomics.net, variablePct: financial.unitEconomics.variable / financial.unitEconomics.net * 100, fixed: A.fixed, setup: A.setup, workingCapital: A.openingUnits * A.product + A.deposit, reserveMonths: A.reserveMonths, collectionLag: 0 };
const scenario = (index: number, multiplier: number) => { const s = financial.scenarios[index]; return { ...base, volume: base.volume * multiplier, price: s.net, variablePct: s.variable / s.net * 100, fixed: s.inputs.fixed }; };
const model: ModelConfig = {
  kind: 'operating', base, capacity: 1000, unit: L('طلب / عبوة 50 مل', 'orders / 50 ml bottles'),
  ramp: financial.monthlyUnits.map(units => units / base.volume), setup, fixed,
  workingCapital: [{ label: L('مخزون افتتاحي: 1,000 عبوة بتكلفة 62 ريالًا', 'Opening stock: 1,000 bottles at SAR 62'), amount: A.openingUnits * A.product }, { label: L('وديعة تخزين', 'Storage deposit'), amount: A.deposit }],
  conservative: scenario(0, .7), optimistic: scenario(2, 1.3),
};

export const AEVU_FEASIBILITY: PortfolioFeasibilityStudy = {
  slug: 'aevu', name: L('إيڤو — AEVU', 'AEVU'), sector: L('عطور للنساء والرجال', 'Fragrance for women and men'),
  hero: '/assets/studies/aevu/landscape.webp', theme: { ink: '#382D42', paper: '#F2EFE8', soft: '#CCD8C2' }, model,
  version: '2026-09-07', download: '/downloads/AEVU-Strategy-Identity-Feasibility.pdf', financialDownload: '/downloads/AEVU-Financial-Model.xlsx',
  evidenceNote: L('لم يُجرَ بحث ميداني أو اختبار بيع أو جمع عروض أسعار. المدخلات التجارية افتراضات من إعداد أثر. رسوم تسجيل طلب علامة واحد مستندة إلى SAIP، والقيمة المضافة إلى ZATCA. المقارنة المكتبية توثق العرض المنشور ولا تثبت الطلب. الإصدار: ', 'No fieldwork, sales test or supplier quotation exercise has been completed. Commercial inputs are ATHR planning assumptions. One trademark request fee is sourced from SAIP and VAT from ZATCA. Desk research records published offers, not demand. Version: '),
  budgetNote: L('القيم بالريال السعودي. التكاليف تقديرية عدا رسوم طلب علامة واحد وفئة واحدة: 6,500 ريال وفق صفحة SAIP. تجهيز الإدراج أتعاب مفترضة؛ خدمة إخطار التسويق لدى SFDA معلنة بلا مقابل. تعديلات الحاسبة لا تغير الجداول الأساسية.', 'SAR amounts are estimates except the published SAR 6,500 fee for one trademark request in one class. Notification preparation is an assumed service allowance; SFDA lists marketing notification without a fee. Calculator edits do not change the base tables.'),
  summary: L('هل يمكن تحويل «نفَس يتّسع» إلى عطر واضح الاختيار، بهامش يتحمل التسويق والتوريد؟', 'Can “A breath, unfolding” become an easy-to-choose fragrance with a margin that supports marketing and supply?'),
  scope: L('مشروع تصوري لمتجر سعودي يبيع عطرًا واحدًا 50 مل بتصنيع تعاقدي. عبوة واحدة لكل طلب. لا مصنع مملوكًا أو متجرًا فعليًا أو بيع جملة أو قالب زجاج حصريًا في الأساس. صور العبوة والتغليف مولدة بالذكاء الاصطناعي لشرح الاتجاه، ولم تستخدم نماذج منتج جاهزة.', 'Concept study for a Saudi online store selling one 50 ml contract-manufactured fragrance, one bottle per order. No owned factory, physical store, wholesale or exclusive glass tooling is included. Product and packaging images are AI-generated direction studies; no stock product mockups were used.'),
  decision: L('اختبار محدود قبل التوسع. التمويل الأساسي 200,000 ريال، مع هامش إضافي تقديري 10,000 ريال لتوقيت الضريبة. الأساس يخطط لـ3,650 طلبًا وإيرادات صافية 712,538 ريالًا وفائض تشغيل 24,360 ريالًا في أول سنة بيع؛ قبل الإهلاك والتمويل والزكاة/ضريبة الدخل، وتكاليف التأسيس منفصلة.', 'Run a limited paid test before scaling. Base funding is SAR 200,000 plus an assumed SAR 10,000 VAT timing buffer. The base plans 3,650 orders, SAR 712,538 net revenue and SAR 24,360 operating surplus in the first selling year, before depreciation, financing and zakat/income tax; setup expenditure is separate.'),
  market: [
    C('الجمهور الأول', 'Initial audience', 'نساء ورجال 25–40 عامًا في المدن السعودية؛ يبحثون عن عطر شخصي للارتداء اليومي وشراء هدية دون تعقيد. العمر والسلوك فرضية اختيار شريحة تحتاج مقابلات، وليسا نتيجة مسح.', 'Women and men aged 25–40 in Saudi cities seeking a personal everyday scent and a straightforward gift. Age and behavior define a segment hypothesis, not a survey result.'),
    C('العرض المنشور', 'Published alternatives', 'لافيرن يقدم ذا ريل باتشولي 100 مل، وقد ظهرت عملة الدولار في اللقطة فلم نعتمدها سعرًا سعوديًا. درعه تعرض دوت ريد 125 مل بـ490 ريالًا وميراج 100 مل بـ520 ريالًا ضمن عروض 1+2 مجانًا؛ السعر المعلن لا يساوي سعر العبوة الفعلي داخل الحزمة.', 'Laverne lists The Real Patchouli 100 ml; the snapshot displayed USD, so it was not treated as a Saudi price. Deraah lists Dot Red 125 ml at SAR 490 and Mirage 100 ml at SAR 520 with buy-one-get-two promotions. Sticker prices are not effective bundle unit prices.'),
    C('كيف نبني الطلب؟', 'Building a demand estimate', 'لا نفترض حجم سوق أو حصة منشورة. 3,650 طلبًا تحتاج 182,500 زيارة سنوية عند تحويل افتراضي 2%. يبدأ اختبار الاكتساب والشراء قبل الالتزام بهذا الحجم.', 'No market size or share is asserted. At an assumed 2% conversion, 3,650 orders require 182,500 annual visits. Test acquisition and purchasing before committing to this volume.'),
  ],
  validation: [
    C('الرائحة والسعر', 'Scent and price', '30 مقابلة شراء و60 تجربة عمياء للرائحة، ثم 100 طلب مدفوع بعد اعتماد المنتج. تقاس أسباب الشراء والرفض واستعداد الدفع، وتوثق العينة والتاريخ.', 'Conduct 30 buying interviews and 60 blind scent trials, then 100 paid orders after product approval. Record purchase and rejection reasons, willingness to pay, sampling and dates.'),
    C('اقتصاد الطلب', 'Order economics', 'راجع التسويق والخصم والمرتجعات وتكلفة التسليم من الطلبات المدفوعة. المساهمة المستهدفة قرابة 56 ريالًا للطلب، والتعادل الأساسي 268 طلبًا شهريًا.', 'Measure marketing, discounts, refunds and delivery costs on paid orders. Target contribution is approximately SAR 56 per order; base break-even is 268 monthly orders.'),
  ],
  offer: [
    C('البداية', 'Initial product', 'تركيبة توقيع واحدة بحجم 50 مل وسعر اختبار 249 ريالًا شامل الضريبة قبل الخصم. عينات التجربة ضمن التطوير، ولا يفترض النموذج إيرادًا من عينات أو اشتراكات.', 'One signature fragrance in 50 ml, tested at SAR 249 including VAT before discounts. Trial samples belong to development; no sample or subscription revenue is modeled.'),
    C('وعد واضح', 'A clear promise', 'رائحة شخصية، واختيار بسيط. يشرح المنتج الإحساس والاستخدام والمكونات المعتمدة بوضوح. لا وعود ثبات أو منشأ أو وصف طبيعي قبل تحققها.', 'A personal scent, a simple choice. Explain the experience, usage and approved ingredients clearly. Longevity, origin and natural-content claims require evidence.'),
  ],
  operations: [
    C('تصنيع تعاقدي', 'Contract manufacturing', 'مورد مؤهل، عينة مرجعية معتمدة، مواصفة للدفعة واختبار توافق التركيبة مع الزجاج والبخاخ. تكلفة 62 ريالًا للعبوة افتراض تفاوضي يحتاج عرضًا.', 'Qualified supplier, approved reference sample, batch specification and formula compatibility tests with glass and pump. SAR 62 per bottle is a planning input requiring a quotation.'),
    C('الجودة والإدراج', 'Quality and notification', 'إعداد بيانات المصنع والمكونات والملصق ومتطلبات إخطار التسويق عبر غد بحسب النشاط. راجع المتطلبات الفعلية مع المختص قبل البيع، وسجل الدفعات والشكاوى.', 'Prepare factory, ingredient and label information and GHAD marketing-notification requirements for the actual activity. Confirm applicable requirements before sale and track batches and complaints.'),
    C('التوريد', 'Supply schedule', '1,000 عبوة افتتاحية مدفوعة وثلاث دفعات من 1,000 في الأشهر 4 و7 و10. مقدم 50% قبل الاستلام بشهر والباقي عنده. نهاية السنة 350 عبوة في الأساس.', '1,000 prepaid opening bottles and three 1,000-bottle deliveries in months 4, 7 and 10. Pay 50% one month ahead and the balance on receipt. Base closing inventory is 350 bottles.'),
  ],
  capacityNote: L('حد الحاسبة 1,000 طلب شهريًا افتراض طاقة، وليس إثباتًا لتعاقد أو طلب. التدرج 150 إلى 450 طلبًا خلال السنة. يلزم تحديث مواعيد التوريد عند تغيير الحجم.', 'The calculator cap of 1,000 monthly orders is a capacity assumption, not a contracted or proven volume. The base ramps from 150 to 450 monthly orders. Changes require a new supply schedule.'),
  collectionNote: L('الحاسبة أدناه تحافظ على المخزون ثابتًا وتدفع تكلفة المنتج المباع في شهره؛ نقد نهاية السنة فيها 84,360 ريالًا. Excel وPDF يفصلان دفعات المورد ويخفضان المخزون من 1,000 إلى 350 عبوة؛ النقد النهائي 124,660 ريالًا، والأدنى 31,581 ريالًا. فرق 40,300 ريال هو انخفاض المخزون بتكلفته، مع تطابق الربحية. تفترض الدراسة التحصيل داخل الشهر ولا تمثل تسوية يومية.', 'The calculator below holds inventory constant and pays for goods sold in the same month, ending with SAR 84,360 cash. Excel and PDF model supplier installments and inventory falling from 1,000 to 350 bottles, ending with SAR 124,660 cash and a SAR 31,581 minimum. The SAR 40,300 difference is inventory reduction at cost; profitability agrees. Collection is assumed within the month, not modeled daily.'),
  assumptions: [
    C('السعر الصافي', 'Net price', '249 × 92% بعد الخصم × 98% بعد الاسترداد ÷ 1.15 = 195.216 ريال إيراد للطلب. المدخل في الحاسبة هو هذا الصافي؛ تغيير سعر المستهلك والخصم كل على حدة متاح في Excel.', '249 × 92% after discount × 98% after refunds ÷ 1.15 = SAR 195.216 net revenue per order. The calculator uses this net input; Excel separates consumer price and discount.'),
    C('تمويل البداية', 'Starting funding', '75,000 تأسيس +62,000 مخزون +3,000 وديعة +60,000 احتياطي =200,000 ريال. يضاف 10,000 تقديريًا لتوقيت الضريبة خارج الحاسبة الأساسية. الاحتياطي ليس مصروفًا.', 'SAR 75,000 setup +62,000 stock +3,000 deposit +60,000 reserve =200,000. Add an assumed SAR 10,000 VAT timing buffer outside the base calculator. A reserve is not an expense.'),
  ],
  variableCosts: L('139.227 ريالًا للطلب: منتج 62، تجهيز 5، شحن 18، رسوم دفع 6.727 (2.5% من المحصل بعد الخصم +1)، معالجة مرتجعات 2.5، وتسويق 45. التسويق متوسط لكل الطلبات وليس تكلفة عميل جديد. رد الإيراد محسوب في السعر الصافي؛ لا يعاد المنتج المرتجع للمخزون.', 'SAR 139.227 per order: product 62, fulfillment 5, shipping 18, payment 6.727 (2.5% of discounted gross +1), returns handling 2.5 and marketing 45. Marketing is blended across all orders, not new-customer CAC. Revenue refunds are included in net price; returned goods are not restocked.'),
  tax: L('سعر المستهلك يتضمن VAT بنسبة 15%. الإيراد والتكاليف في النموذج صافية مع افتراض استرداد المدخلات المؤهلة. توقيت إقرارات الضريبة والتسوية غير محسوب؛ هامش 10,000 ريال تقديري يحتاج مراجعة محاسبية. الفائض قبل الإهلاك والتمويل والزكاة/ضريبة الدخل.', 'Consumer price includes 15% VAT. Model revenue and costs are net, assuming eligible input VAT is recoverable. Filing and settlement timing are excluded; the SAR 10,000 buffer requires accounting review. Surplus precedes depreciation, financing and zakat/income tax.'),
  risks: [
    C('قبول ضعيف', 'Weak acceptance', 'تجربة كثيرة وشراء قليل: راجع الرائحة والسعر ووضوح الوصف. لا تعالج ضعف الطلب بزيادة دفعات التصنيع.', 'Many trials but few purchases: revisit scent, price and description. Do not respond to weak demand with larger production batches.'),
    C('ضغط التسويق', 'Marketing pressure', 'المتحفظ يخفض الحجم 30% ويرفع التسويق والمنتج؛ ينتج عجزًا تشغيليًا يقارب 138 ألف ريال. راقب مساهمة كل قناة قبل رفع الإنفاق.', 'The conservative case reduces volume by 30% while increasing marketing and product costs, producing an approximately SAR 138,000 operating deficit. Track channel contribution before scaling spend.'),
    C('المخزون والسيولة', 'Inventory and cash', 'حدّث خطة نقد أسبوعية ومواعيد المورد. انخفاض مخزون الأمان أو تأخر التسليم أو تسرب الدفعة يستدعي إبطاء الإعلان والتحقق من التوريد والجودة.', 'Update weekly cash and supplier schedules. Low safety stock, delays or leaks require slower advertising and a supply or quality review.'),
  ],
  gates: [
    C('قبل طلب الدفعة', 'Before the first batch', 'فحص توافر الاسم، اعتماد العينة والملصق، عروض تصنيع وشحن مكتوبة، ومسؤولية واضحة للجودة والإدراج والمرتجعات.', 'Name-availability checks, approved sample and label, written manufacturing and shipping quotes, and clear ownership of quality, notification and returns.'),
    C('بعد 100 طلب', 'After 100 orders', 'مساهمة فعلية لا تقل عن 45 ريالًا للطلب، وتسليم في الموعد 92% فأكثر، وإيراد مسترد لا يزيد على 4%؛ أهداف قبول مقترحة لا نتائج محققة.', 'Actual contribution of at least SAR 45 per order, at least 92% on-time delivery and revenue refunds no higher than 4%: proposed acceptance targets, not achieved results.'),
    C('قبل التوسع', 'Before scaling', 'تغطية نقدية لـ13 أسبوعًا وثلاثة أشهر مساهمة مستقرة. يؤجل التوسع عند فشل الاقتصاد أو عدم كفاية التوريد أو متطلبات البيع.', 'Thirteen-week cash coverage and three months of stable contribution. Defer scaling if economics, supply or sale requirements are not satisfied.'),
  ],
  brand: [
    C('نفَس يتّسع', 'A breath, unfolding', 'الفكرة من انتقال أثر العطر من نقطة إلى مساحة. أقواس U المتداخلة تصبح تفصيلًا على الزجاج والعلبة وإطارًا للصور؛ AEVU حروف واضحة متينة، مع معالجة عربية صحيحة «إيڤو».', 'The concept follows scent expanding from a point into space. Nested U curves become a glass and packaging detail and an image frame. AEVU uses clear, sturdy letterforms with the Arabic name إيڤو.'),
    C('اللون والخط', 'Color and type', 'باذنجاني #382D42 للعمق، أخضر ضبابي #CCD8C2 للهواء، عاجي #F2EFE8 للوضوح، وفضي رمادي #B6B9B7 للمادة. IBM Plex Sans Arabic وManrope للنصوص المساندة؛ الشعار يحتاج رسمًا متجهيًا نهائيًا واختبار تصغير.', 'Aubergine #382D42 adds depth, mist sage #CCD8C2 suggests air, ivory #F2EFE8 brings clarity and silver gray #B6B9B7 expresses material. Supporting type: IBM Plex Sans Arabic and Manrope. Final logo production requires vector drawing and small-size testing.'),
  ],
  sources: [
    {title:L('لافيرن — ذا ريل باتشولي','Laverne — The Real Patchouli'),url:'https://laverne.com/ar/oZdXBGY',purpose:L('المنتج والحجم والعرض المنشور؛ لا تحويل لسعر الدولار إلى ريال في المقارنة.','Published product, size and offer; the displayed USD price was not converted into a Saudi comparison price.')},
    {title:L('درعه — عطور للجنسين','Deraah — Unisex fragrances'),url:'https://www.deraahstore.com/ar_sa/perfumes/unisex-perfumes',purpose:L('لقطة أسعار وأحجام وحزم، لا مبيعات محققة أو حجم سوق.','A snapshot of prices, sizes and bundles, not actual sales or market size.')},
    {title:L('SFDA — إخطار تسويق منتجات التجميل','SFDA — Cosmetic marketing notification'),url:'https://www.sfda.gov.sa/ar/eservices/307',purpose:L('بيانات غد والمصنع والمنتج؛ صفحة الخدمة تعرضها بلا مقابل.','GHAD, factory and product information; the service is listed without a fee.')},
    {title:L('SAIP — تسجيل علامة تجارية','SAIP — Trademark registration'),url:'https://www.saip.gov.sa/ar/services/trademarks/trademark-registration',purpose:L('1,000 طلب +500 نشر +5,000 تسجيل؛ لا يثبت توافر AEVU.','1,000 application +500 publication +5,000 registration; this does not establish AEVU availability.')},
    {title:L('ZATCA — القيمة المضافة','ZATCA — VAT'),url:'https://zatca.gov.sa/en/HelpCenter/FAQs/Pages/FAQArchiveEservices.aspx?cat=10',purpose:L('مرجع نسبة الضريبة؛ المعالجة النهائية بحسب وضع المنشأة وفواتيرها.','VAT rate reference; final treatment depends on the entity and its invoices.')},
    {title:L('وزارة التجارة — توثيق التجارة الإلكترونية','Ministry of Commerce — E-commerce authentication'),url:'https://mc.gov.sa/ar/mediacenter/News/Pages/29-03-23-02.aspx',purpose:L('جهة خدمة التوثيق؛ راجع متطلبات النشاط عند الإطلاق.','Authentication service authority; confirm actual requirements at launch.')},
    {title:L('سدايا — سياسة الخصوصية','SDAIA — Privacy policy'),url:'https://dgp.sdaia.gov.sa/wps/portal/pdp/knowledgecenter/details/ElaborationandDevelopingPrivacyPolicyGuideline',purpose:L('الإفصاح عند جمع البيانات وإعداد السياسة.','Collection notices and privacy policy preparation.')},
  ],
};
