import { AEVU_FEASIBILITY } from './aevu';
import { bilingual as L, type BudgetRow, type ModelConfig, type ModelInputs } from '@/lib/portfolio-feasibility-model';
import type { PortfolioFeasibilityStudy, StudyCard, StudySource } from './types';

const C = (ar: string, en: string, bodyAr: string, bodyEn: string): StudyCard => ({ title: L(ar, en), body: L(bodyAr, bodyEn) });
const B = (ar: string, en: string, amount: number): BudgetRow => ({ label: L(ar, en), amount });
const total = (rows: BudgetRow[]) => rows.reduce((sum, row) => sum + row.amount, 0);
const method: StudySource = {
  title: L('SBA — تخطيط المشروع والتكاليف', 'SBA — Business planning and costs'),
  url: 'https://www.sba.gov/counseling/plan-your-business/',
  purpose: L('مرجع عام للفصل بين تكاليف البداية والتشغيل ومنهج التعادل؛ لا يثبت أي سعر أو طلب في السعودية.', 'General guidance on startup versus operating costs and break-even; it does not substantiate Saudi prices or demand.'),
};
const vat: StudySource = {
  title: L('هيئة الزكاة والضريبة والجمارك — القيمة المضافة', 'ZATCA — Value Added Tax'),
  url: 'https://zatca.gov.sa/ar/RulesRegulations/VAT/Pages/default.aspx',
  purpose: L('مرجع للتحقق من المعالجة الضريبية والتسجيل؛ أسعار هذا النموذج وإيراداته مستبعدة منها القيمة المضافة.', 'Reference for confirming VAT treatment and registration; model prices and revenues exclude VAT.'),
};
const privacy: StudySource = {
  title: L('سدايا — دليل إعداد سياسة الخصوصية', 'SDAIA — Privacy policy guidance'),
  url: 'https://dgp.sdaia.gov.sa/wps/portal/pdp/knowledgecenter/details/ElaborationandDevelopingPrivacyPolicyGuideline',
  purpose: L('مرجع لإعداد سياسة الخصوصية والإفصاح عند جمع البيانات؛ لا يعني أن منصة وِزان حصلت على اعتماد.', 'Guidance for privacy notices at collection; this does not imply that WIZAN is certified.'),
};
const netTax = L('القيم قبل ضريبة القيمة المضافة. نفترض استبعاد ضريبة المدخلات القابلة للاسترداد من التكلفة، ولا نحسب توقيت سدادها أو استردادها. يُضاف التمويل المؤقت للضريبة بعد مراجعة التسجيل والفواتير الفعلية.', 'Amounts exclude VAT. Costs assume recoverable input VAT is excluded; settlement and refund timing are not modeled. Temporary VAT funding must be added after reviewing registration and actual invoices.');

function operating(base: ModelInputs, capacity: number, unit: ReturnType<typeof L>, setup: BudgetRow[], fixed: BudgetRow[], workingCapital: BudgetRow[], ramp: number[], conservative: ModelInputs, optimistic: ModelInputs): ModelConfig {
  const inputs = { ...base, setup: total(setup), fixed: total(fixed), workingCapital: total(workingCapital) };
  return { kind: 'operating', base: inputs, unit, capacity, setup, fixed, workingCapital, ramp, conservative: { ...inputs, ...conservative }, optimistic: { ...inputs, ...optimistic } };
}

const athrModel = operating(
  { volume: 6, price: 12000, variablePct: 25, reserveMonths: 3, collectionLag: 1 }, 8, L('مشروع مكتمل', 'completed projects'),
  [B('أجهزة وبرامج إنتاج أولية', 'Initial production hardware and software', 35000), B('تهيئة مساحة العمل', 'Workspace setup', 15000), B('تجهيز قوالب وتسليمات وموقع', 'Templates, delivery system and website', 10000), B('إجراءات وتدريب وتهيئة', 'Administration, training and launch preparation', 8000), B('تجاوز تأسيس مفترض', 'Assumed setup contingency', 7000)],
  [B('أجر المؤسس العامل', 'Working founder allowance', 12000), B('فريق التصميم وإدارة المشاريع', 'Design and project management team', 18000), B('مساحة العمل', 'Workspace', 4000), B('برامج واشتراكات', 'Software subscriptions', 2500), B('تسويق وتطوير أعمال', 'Marketing and business development', 5000), B('محاسبة وإدارة', 'Accounting and administration', 2500), B('اتصال ومصاريف مساندة', 'Connectivity and support costs', 1000)],
  [B('وديعة مساحة العمل', 'Workspace deposit', 15000)],
  [.4, .5, .65, .75, .85, .9, 1, 1, 1, 1, 1, 1],
  { volume: 4, price: 11000, variablePct: 30, collectionLag: 2 },
  { volume: 8, price: 13500, variablePct: 25, fixed: 49000, collectionLag: 1 },
);

const deliveryModel = operating(
  { volume: 4500, price: 25, variablePct: 35, reserveMonths: 4, collectionLag: 1 }, 6000, L('توصيلة مدفوعة مكتملة', 'completed billable deliveries'),
  [B('نظام متابعة وربط المتاجر', 'Tracking system and merchant integration', 35000), B('تهيئة نقطة تجميع وفرز', 'Collection and sorting point setup', 20000), B('أجهزة مسح واتصال وسلامة', 'Scanning, communications and safety equipment', 15000), B('تدريب وإجراءات وتجارب مسارات', 'Training, administration and route trials', 12000), B('هوية وتطبيقات تشغيل', 'Identity and operating applications', 8000), B('تجاوز تأسيس مفترض', 'Assumed setup contingency', 10000)],
  [B('أجور السائقين ضمن النطاق الأساسي', 'Driver payroll within the base scope', 30000), B('تنسيق ومتابعة وخدمة عملاء', 'Dispatch and customer service', 8000), B('إيجار المركبات', 'Vehicle leases', 12000), B('إدارة وأجر مالك عامل', 'Management and working owner allowance', 7000), B('نقطة التجميع', 'Collection point rent', 4000), B('أنظمة وتأمين وإدارة', 'Systems, insurance and administration', 4000)],
  [B('ودائع مركبات وموقع', 'Vehicle and premises deposits', 45000), B('مستهلكات افتتاحية', 'Opening consumables', 5000)],
  [.3, .4, .55, .65, .8, .9, 1, 1, 1, 1, 1, 1],
  { volume: 3300, price: 23, variablePct: 40, collectionLag: 2 },
  { volume: 5600, price: 26, variablePct: 33, fixed: 71000, collectionLag: 1 },
);

const toysModel = operating(
  { volume: 1000, price: 130, variablePct: 58, reserveMonths: 4, collectionLag: 0 }, 1500, L('فاتورة', 'transactions'),
  [B('تجهيز المتجر والأرفف', 'Store fit-out and shelving', 105000), B('نقطة بيع ومتجر إلكتروني', 'Point of sale and online store', 25000), B('هوية ولوحات وتغليف', 'Identity, signage and packaging design', 25000), B('عرض تجريبي وتدريب وإجراءات', 'Demonstration setup, training and administration', 25000), B('تجاوز تأسيس مفترض', 'Assumed setup contingency', 20000)],
  [B('فريق المتجر وأجر مدير عامل', 'Store team and working manager allowance', 24000), B('الإيجار', 'Rent', 12000), B('تسويق محلي', 'Local marketing', 6000), B('مرافق وأنظمة', 'Utilities and systems', 4000), B('إدارة وتأمين وصيانة', 'Administration, insurance and maintenance', 4000)],
  [B('مخزون ألعاب افتتاحي بتكلفة الشراء', 'Opening toy inventory at purchase cost', 120000), B('وديعة إيجار', 'Rental deposit', 36000)],
  [.4, .5, .6, .7, .8, .9, 1, 1, 1, 1, 1, 1],
  { volume: 700, price: 120, variablePct: 62, fixed: 51000 },
  { volume: 1300, price: 140, variablePct: 56, fixed: 55000 },
);

const medicalModel = operating(
  { volume: 650, price: 230, variablePct: 18, reserveMonths: 6, collectionLag: 0 }, 1000, L('زيارة مدفوعة', 'paid visits'),
  [B('تهيئة الموقع والأعمال الطبية', 'Premises fit-out and clinical works', 350000), B('تجهيزات غرف الفحص', 'Examination room equipment', 150000), B('أنظمة المواعيد والسجلات والأمن', 'Scheduling, records and security systems', 60000), B('هوية وإرشاد مكاني وموقع', 'Identity, wayfinding and website', 30000), B('تهيئة تراخيص وتوظيف وتدريب', 'Licensing preparation, recruitment and training', 60000), B('تجاوز تأسيس مفترض', 'Assumed setup contingency', 65000)],
  [B('كوادر طبية وتمريضية', 'Clinical and nursing payroll', 66000), B('استقبال وإدارة تشغيل', 'Reception and operating management', 14000), B('إيجار الموقع', 'Premises rent', 15000), B('نظافة ونفايات وصيانة', 'Cleaning, waste and maintenance', 6000), B('أنظمة وتأمين وإدارة', 'Systems, insurance and administration', 5000), B('تعريف بالخدمات ومرافق', 'Service communications and utilities', 4000)],
  [B('وديعة إيجار', 'Rental deposit', 45000), B('مستهلكات افتتاحية', 'Opening clinical consumables', 25000)],
  [.3, .4, .5, .6, .7, .8, .9, 1, 1, 1, 1, 1],
  { volume: 450, price: 210, variablePct: 22, fixed: 115000, collectionLag: 1 },
  { volume: 850, price: 245, variablePct: 18, fixed: 120000, collectionLag: 0 },
);

const wizanSetup = [B('تطوير النسخة الأولى وتجربة الاستخدام', 'Initial product and experience development', 110000), B('محتوى تأسيسي ومراجعة تخصصية', 'Initial content and specialist review', 20000), B('تهيئة خصوصية وأمن وعقود', 'Privacy, security and contract setup', 20000), B('اكتساب مشتركي التجربة الأولية', 'Initial pilot subscriber acquisition', 10000), B('تجاوز تأسيس مفترض', 'Assumed setup contingency', 20000)];
const wizanFixed = [B('إدارة المنتج وأجر مؤسس عامل', 'Product management and working founder allowance', 8000), B('صيانة تقنية ودعم أساسي', 'Engineering maintenance and baseline support', 6000), B('تحرير ومراجعة محتوى', 'Content editing and review', 4000), B('أدوات ومتابعة أمن وخصوصية وإدارة', 'Tools, security, privacy and administration', 4000)];
const wizanBase = { startingUsers: 100, newUsers: 60, churnPct: 5, price: 69, variablePerUser: 10, acquisitionCost: 100, fixed: total(wizanFixed), setup: total(wizanSetup), workingCapital: 0, reserveMonths: 8 };
const wizanModel: ModelConfig = { kind: 'subscription', base: wizanBase, unit: L('مشترك مدفوع', 'paying subscribers'), capacity: 2000, setup: wizanSetup, fixed: wizanFixed, workingCapital: [], conservative: { ...wizanBase, newUsers: 35, churnPct: 9, price: 59, acquisitionCost: 140 }, optimistic: { ...wizanBase, newUsers: 90, churnPct: 3, price: 75, acquisitionCost: 90, fixed: 26000 } };
const propertyBase = { units: 10, soldUnits: 10, price: 850000, land: 1800000, construction: 3600000, professional: 450000, contingencyPct: 10, fixed: 18000, salesPct: 3, taxAllowance: 550000, delay: 0, funding: 6000000 };
const propertyModel: ModelConfig = { kind: 'development', base: propertyBase, unit: L('وحدة سكنية', 'residential units'), capacity: 10, setup: [], fixed: [], workingCapital: [], conservative: { ...propertyBase, soldUnits: 8, price: 790000, construction: 4140000, delay: 3 }, optimistic: { ...propertyBase, price: 920000, construction: 3500000 }, };

export const PORTFOLIO_FEASIBILITY: PortfolioFeasibilityStudy[] = [
  {
    slug: 'athrbrands', name: L('أثر', 'ATHR'), sector: L('استوديو استراتيجيات وهويات', 'Strategy and identity studio'), hero: '/assets/studies/athrbrands/mark.webp', theme: { ink: '#161616', paper: '#F0EADF', soft: '#E1D7C8' }, model: athrModel,
    summary: L('هل يستطيع استوديو صغير تقديم استراتيجية وهوية بجودة ثابتة، مع تسعير يغطي وقت الفريق والتحصيل؟', 'Can a small studio deliver consistent strategy and identity work at a fee that covers team time and collection delays?'),
    scope: L('أثر علامة قائمة، لكن هذه دراسة تدريبية لتكوين تشغيلي افتراضي؛ ليست بيانات أثر الفعلية أو أسعار خدماته أو رواتب فريقه. النطاق فريق صغير ومساحة عمل واحدة ومشاريع محددة التسليم.', 'ATHR is an existing brand, but this is an illustrative operating configuration, not its actual accounts, service prices or team salaries. Scope: a small team, one workspace and clearly scoped projects.'),
    decision: L('يُختبر النموذج بعقود مدفوعة وقياس ساعات التنفيذ قبل زيادة الفريق. ارتفاع الفائض في الشهر المستقر لا يكفي إذا استهلك تأخر التحصيل سيولة الأشهر الأولى.', 'Test paid contracts and delivery hours before expanding the team. A positive steady month is insufficient if collection delays exhaust early cash.'),
    market: [
      C('العميل الأول', 'Initial customer', 'مؤسس مشروع خدمي أو تجاري يستعد للإطلاق ويحتاج قرار تموضع ونظام هوية وتسليمًا منظمًا. تُختار شريحة واحدة أولًا لتقليل اختلاف النطاق بين المشاريع.', 'A service or retail founder preparing to launch who needs positioning, an identity system and structured handover. Start with one segment to limit variation between projects.'),
      C('البدائل والمنافسة', 'Alternatives and competition', 'البدائل: مستقل، وكالة متكاملة، فريق داخلي أو قالب جاهز. نقارن وضوح النطاق وعمق التفكير وموعد التسليم والدعم، لا عدد الشعارات في العرض.', 'Alternatives include freelancers, agencies, internal teams and templates. Compare scope clarity, strategic depth, delivery time and support, rather than the number of logo options.'),
      C('حجم السوق المطلوب', 'Required addressable demand', 'لا نفترض حصة سوق منشورة. يبدأ تقدير الطلب من عدد العملاء المؤهلين ونسبة التعاقد والطاقة المتاحة؛ ستة مشاريع مكتملة شهريًا هدف اختبار، لا مبيعات محققة.', 'No published market share is assumed. Build demand from qualified opportunities, conversion and delivery capacity; six completed projects a month is a test target, not achieved sales.'),
    ],
    validation: [
      C('مقابلات شراء', 'Buying interviews', 'مقابلة اثني عشر مؤسسًا من الشريحة المختارة وتوثيق آخر قرار شراء وميزانيته الفعلية وأسباب التعثر؛ يتولى المؤسس المقابلات خلال أسبوعين.', 'Interview twelve founders in the chosen segment about their last purchase, actual budget and friction. The founder owns this two-week exercise.'),
      C('اختبار عرض مدفوع', 'Paid offer test', 'إرسال عرض ثابت النطاق لعشر فرص مؤهلة، ثم تنفيذ ثلاثة عقود تجريبية. نسجل التحويل والخصم وساعات العمل ومرات التعديل والتحصيل.', 'Offer a defined scope to ten qualified prospects, then deliver three paid pilots. Track conversion, discounts, hours, revisions and collections.'),
    ],
    offer: [
      C('الحزمة الأساسية', 'Core package', 'تشخيص وتموضع ورسائل ونظام هوية ودليل وتسليم. متوسط إيراد المشروع افتراض موزون؛ لا يشمل إنتاج المطبوعات أو شراء المساحات الإعلانية.', 'Discovery, positioning, messaging, identity system, guide and handover. The average project fee is an assumed blended value; printing and media purchases are excluded.'),
      C('ضبط النطاق', 'Scope control', 'تحدد العقود المخرجات ومراحل الاعتماد وعدد جولات التعديل. أي تطبيق إضافي أو إعادة توجيه بعد الاعتماد يُسعّر بنطاق منفصل.', 'Contracts specify deliverables, approval stages and revision rounds. Additional applications or a new direction after approval require a separate scope.'),
      C('الإيراد المتكرر', 'Recurring revenue', 'عقود إدارة الهوية فرصة لاحقة، ولا تدخل إيراد الأساس. إدخالها يستلزم فصل ساعات الخدمة الشهرية عن طاقة المشاريع الجديدة.', 'Brand stewardship retainers are a later opportunity and excluded from the base revenue. Adding them requires reserving monthly service hours separately from new projects.'),
    ],
    operations: [
      C('تسلسل التسليم', 'Delivery flow', 'تأهيل ثم تشخيص ثم استراتيجية ثم تصميم ثم تطبيقات وتسليم. لكل مرحلة مسؤول واعتماد يمنع تراكم تعديلات غير محسوبة.', 'Qualification, discovery, strategy, design, applications and handover. Every stage needs an owner and approval to prevent unbudgeted revisions.'),
      C('الموارد', 'Resources', 'المؤسس يقود الاستراتيجية والمبيعات، والفريق ينفذ التصميم وإدارة المشاريع. يستدعى مستقلون للتخصصات الإضافية ضمن التكلفة المتغيرة.', 'The founder leads strategy and sales; the team handles design and project management. Specialists are commissioned within variable costs.'),
      C('خطة الإطلاق', 'Launch plan', 'أسبوعان للتحقق من الشريحة، ثم شهر للعقود التجريبية وقياس الساعات، ثم ثلاثة أشهر لضبط التعاقد والتحصيل قبل الالتزام بتوظيف إضافي.', 'Two weeks to validate the segment, one month for paid pilots and time tracking, then three months to refine contracts and collections before more hiring.'),
    ],
    capacityNote: L('السقف الافتراضي ثمانية مشاريع مكتملة في الشهر. ليس وعد تسليم؛ تُراجع ساعات كل مرحلة والعمل المتزامن والإجازات قبل اعتماده. الحجم الكسري يمثل متوسطًا تخطيطيًا.', 'Assumed capacity is eight completed projects per month, not a delivery promise. Validate stage hours, concurrent work and leave. Fractional volumes represent planning averages.'),
    collectionNote: L('الأساس يفترض استحقاق كامل الإيراد عند اكتمال المشروع وتحصيله في الشهر التالي، دون ذمم افتتاحية. الدفعات المقدمة والعقود المرحلية تحتاج جدولًا مختلفًا؛ يعرض النموذج الذمم التي لم تُحصّل في نهاية السنة.', 'The base recognizes the full fee at completion and collects it the following month, with no opening receivables. Advances and milestone billing need a different schedule; year-end uncollected receivables are shown.'),
    assumptions: [C('الإيراد والوقت', 'Fee and time', 'مصدر السعر والحجم هو افتراض الدراسة. يستبدله مدير الاستوديو بعقود فعلية وساعات موثقة، ويعيد الحساب شهريًا.', 'Price and volume originate in this study’s assumptions. The studio manager should replace them with signed contracts and logged hours, reviewing monthly.'), C('الأجور والمقر', 'Payroll and premises', 'ميزانية افتراضية تشمل أجر المؤسس العامل؛ لا تمثل كشف أجور أثر. تحتاج عروض عمل وإيجار وبرامج قبل الاعتماد.', 'The hypothetical budget includes a working-founder allowance and is not ATHR payroll. Obtain hiring, rent and software quotations before approval.')],
    variableCosts: L('نسبة متغيرة مفترضة: عشرون بالمئة للتخصصات الخارجية وخمسة بالمئة للإنتاج والتسليم وإعادة العمل. رواتب الفريق الأساسي ضمن الثابت، ولا تُعد مرة ثانية.', 'Assumed variable mix: twenty percent external specialists and five percent production, handover and rework. Core team payroll is fixed and not counted again.'), tax: netTax,
    risks: [C('توسع النطاق', 'Scope expansion', 'المؤشر: ساعات فعلية أعلى من المقدر. الإجراء: اعتماد مرحلي وأوامر تغيير وتسعير بحسب الوقت والمخرجات.', 'Signal: actual hours exceed estimates. Response: stage approvals, change orders and pricing tied to time and deliverables.'), C('تركيز العملاء والتحصيل', 'Concentration and collections', 'المؤشر: عميل واحد يستهلك أغلب الطاقة أو دفعات متأخرة. الإجراء: حدود ائتمان وتنويع العملاء ومراجعة أعمار الذمم أسبوعيًا.', 'Signal: one client dominates capacity or payments are late. Response: credit limits, diversified clients and weekly receivables review.')],
    gates: [C('المضي', 'Proceed', 'بعد ثبوت مساهمة موجبة في العقود التجريبية، وتوفر فرص تكفي التعادل داخل الطاقة، وتمويل يغطي أدنى رصيد مع هامش طوارئ.', 'Proceed after pilots demonstrate positive contribution, the pipeline supports break-even within capacity and funding covers the lowest cash balance plus contingency.'), C('التعديل أو التأجيل', 'Revise or defer', 'تُراجع الحزمة أو السعر إذا لم تغط ساعاتها. يؤجل التوسع إذا تجاوز التعادل الطاقة أو بقي التحصيل بلا شروط قابلة للتنفيذ.', 'Revise scope or pricing when fees do not cover time. Defer expansion if break-even exceeds capacity or collection terms remain unworkable.')],
    brand: [C('وعد يمكن تنفيذه', 'A deliverable promise', 'تترجم الجدوى وعد العمق والوضوح إلى مراحل معلنة وحدود تسليم، مع أمثلة توضح ما يشتريه العميل.', 'Translate depth and clarity into explicit stages and delivery boundaries, with examples of what the client buys.'), C('أولوية التطبيقات', 'Application priorities', 'تبدأ الهوية بعرض السعر ونموذج التشخيص وخطة المشروع والدليل وقالب التسليم؛ ثم الحملات بعد استقرار التنفيذ.', 'Prioritize proposals, discovery forms, project plans, guides and handover templates; expand campaigns after delivery stabilizes.')],
    sources: [method, vat],
  },
  AEVU_FEASIBILITY,
  {
    slug: 'tatabu', name: L('تَتابُع', 'TATABU'), sector: L('توصيل محلي للمتاجر', 'Local merchant delivery'), hero: '/assets/studies/tatabu/hero.webp', theme: { ink: '#15212D', paper: '#F1F4F7', soft: '#DEE5FF' }, model: deliveryModel,
    summary: L('هل تحقق كثافة الطلبات في نطاق محلي تكلفة توصيل يمكن تغطيتها، مع حالة واضحة للطلب وتحويل النقد في موعده؟', 'Can local route density support delivery economics while keeping parcel status clear and collections on time?'),
    scope: L('مشروع تصوري لتوصيل طرود متاجر داخل نطاق مدينة محدد، بمركبات مستأجرة وفريق أساسي. لا يشمل شبكة شحن وطنية أو تخليصًا جمركيًا أو تبريدًا أو تحصيل مبالغ البضاعة نيابة عن التاجر.', 'A concept parcel operation within a defined city area, using leased vehicles and a core team. National freight, customs, cold chain and collecting merchandise cash for merchants are excluded.'),
    decision: L('شرط الجدوى كثافة مسارات قابلة للتكرار وعقود تتضمن حدًا واضحًا للمحاولات والتحصيل. يُختبر نطاق واحد قبل إضافة أحياء بعيدة أو الالتزام بزمن تسليم قصير.', 'Feasibility depends on repeatable route density and contracts defining attempts and payment terms. Pilot one area before adding distant districts or promising shorter delivery times.'),
    market: [C('العميل الدافع', 'Paying customer', 'متجر يرسل طرودًا متكررة ويحتاج رؤية حالة الطلب وتقليل اتصالات المتابعة. المستلم مستخدم للخدمة، لكن التاجر هو العميل الدافع في الأساس.', 'A merchant shipping regularly who needs shipment visibility and fewer follow-up calls. The recipient uses the service, but the merchant is the base paying customer.'), C('البدائل', 'Alternatives', 'شركة طرود أو أسطول متجر أو مزود توصيل فوري. نقارن تكلفة التوصيلة المكتملة والمناطق والاستثناءات وإثبات التسليم وسرعة تسوية المطالبات.', 'Alternatives include parcel carriers, merchant fleets and on-demand providers. Compare completed-delivery cost, coverage, exceptions, proof of delivery and claim resolution.'), C('بناء الطلب', 'Building demand', 'نبدأ بعدد متاجر ملتزمة وحجم يومي موثق لكل متجر. عدد الطرود المسجلة لا يساوي عدد التوصيلات المكتملة القابلة للفوترة.', 'Start from committed merchants and documented daily volume per merchant. Registered parcels are not the same as completed billable deliveries.')],
    validation: [C('تجربة مسارات', 'Route pilot', 'اختبار أربعة أسابيع مع خمسة متاجر وفي نطاق واحد. يسجل مسؤول التشغيل الزمن والمسافة والتوقفات والمحاولات الفاشلة والتلف لكل مسار.', 'Run a four-week pilot with five merchants in one area. Operations records time, distance, stops, failed attempts and damage by route.'), C('اختبار تعاقد', 'Contract test', 'تأكيد السعر والحد الأدنى والوزن والمناطق وعدد المحاولات وموعد التحصيل بعرض مكتوب. لا تُحسب نوايا الاهتمام حجمًا مضمونًا.', 'Confirm price, minimum volume, weight, coverage, attempt limits and payment timing in writing. Expressions of interest are not guaranteed volume.')],
    offer: [C('خدمة أساسية', 'Core service', 'استلام مجدول وفرز وتسليم محلي مع إثبات وحالة قابلة للمتابعة. السعر المتوسط لتوصيلة مدفوعة مكتملة؛ التعويضات والاستثناءات موثقة في العقد.', 'Scheduled collection, sorting and local delivery with proof and tracking. Average revenue is per completed billable delivery; compensation and exceptions must be contractual.'), C('إضافات منفصلة', 'Separate extras', 'المرتجع والمحاولة الإضافية والأحجام الكبيرة تحتاج تسعيرًا مستقلًا. لا نفترض أن رسومها إيراد إضافي مضمون في الحاسبة.', 'Returns, extra attempts and oversized parcels need separate pricing. Their fees are not assumed as guaranteed extra revenue in the calculator.'), C('تحصيل الخدمة', 'Service collections', 'تُفصل فاتورة رسوم التوصيل عن قيمة بضائع التاجر. إدخال الدفع عند الاستلام مستقبلًا يتطلب دفتر أمانات وتسوية مستقلين.', 'Separate delivery service invoices from merchant merchandise value. Future cash-on-delivery operations require separate custody and reconciliation records.')],
    operations: [C('التنفيذ', 'Execution', 'مسح عند الاستلام، فرز بحسب المنطقة، تسليم للسائق، توثيق المحاولة، ثم إغلاق الحالة وتسوية المطالبة. لكل طرد مسؤول وحالة تالية واضحة.', 'Scan at collection, sort by area, hand over to the driver, document attempts, then close the status and reconcile claims. Every parcel needs an owner and next status.'), C('التكلفة والطاقة', 'Cost and capacity', 'ميزانية أساس لستة سائقين ومركبات مستأجرة وتنسيق مركزي. الرواتب والإيجارات ثابتة؛ الوقود والاستهلاك والاستثناءات مرتبطة بالحجم.', 'The base budgets six drivers, leased vehicles and centralized dispatch. Payroll and leases are fixed; fuel, wear and exceptions vary with volume.'), C('الترخيص ونطاق النشاط', 'Licensing and activity scope', 'يُحسم لدى الهيئة العامة للنقل تصنيف الخدمة وترخيصها قبل التعاقد والتشغيل، بحسب نقل الطرود وطريقة إسناد التوصيل. هذه الدراسة لا تثبت أهلية أو ترخيصًا.', 'Confirm the activity classification and licensing with TGA before contracts and operations, based on parcel transport and delivery assignment. This study establishes no eligibility or licence.')],
    capacityNote: L('السقف الافتراضي ستة آلاف توصيلة مكتملة شهريًا. يُراجع باختبار المسارات وأيام العمل والورديات، ولا تعني زيادة الطلب توفر الطاقة تلقائيًا. تغيير النطاق الجغرافي يستلزم إعادة التكلفة.', 'Assumed capacity is six thousand completed deliveries monthly. Validate route trials, working days and shifts; more demand does not automatically create capacity. Geographic expansion requires recosting.'),
    collectionNote: L('الأساس يحصّل رسوم الخدمة بعد شهر من التنفيذ ويدفع تكاليف التشغيل في شهرها، دون ذمم افتتاحية. السيناريو المتحفظ يختبر شهرين. لا توجد مبالغ بضائع أو أموال أمانة ضمن الإيرادات.', 'The base collects service fees one month after delivery and pays costs in the current month, with no opening receivables. The conservative case tests two months. Merchandise and custody funds are excluded from revenue.'),
    assumptions: [C('الحجم والكثافة', 'Volume and density', 'افتراضات حجم وسعر تحتاج سجل طرود وعقودًا. يعيد مدير التشغيل حساب تكلفة التوصيلة المكتملة أسبوعيًا مع فصل المحاولات الفاشلة.', 'Volume and price assumptions require parcel logs and contracts. Operations reviews completed-delivery cost weekly, separating failed attempts.'), C('المركبات والعمالة', 'Fleet and staff', 'تكاليف تقديرية تحتاج عروض إيجار وتأمين وتوظيف ونطاق صيانة. لا يتضمن التأسيس شراء المركبات لأن الأساس يستأجرها.', 'Estimated costs require lease, insurance and employment offers with maintenance scope. Setup excludes vehicle purchases because the base leases them.')],
    variableCosts: L('مزيج متغير مفترض: خمسة عشر بالمئة وقود واستهلاك وصيانة حجمية، وعشرة استثناءات ومحاولات، وخمسة مستهلكات وربط، وخمسة تعويضات ومساندة وقت الذروة. أجور الفريق الأساسي وإيجار المركبات ثابتة.', 'Assumed variable mix: fifteen percent fuel, wear and volume-related maintenance; ten exceptions and attempts; five consumables and integration; five claims and peak support. Core payroll and vehicle leases stay fixed.'), tax: netTax,
    risks: [C('ضعف الكثافة', 'Low route density', 'المؤشر: مسافة كبيرة لكل تسليم أو وقت انتظار مرتفع. الإجراء: تضييق النطاق ومواعيد تجميع ثابتة وحد أدنى تعاقدي.', 'Signal: high distance per delivery or long waiting times. Response: tighter coverage, fixed collection windows and contractual minimums.'), C('الجودة والذمم', 'Quality and receivables', 'المؤشر: ارتفاع فشل التسليم أو مطالبة قديمة بلا إغلاق. الإجراء: إثبات تسليم واضح وسجل استثناءات وحد ائتماني للتاجر.', 'Signal: increasing delivery failure or unresolved aged claims. Response: clear delivery evidence, exception logs and merchant credit limits.')],
    gates: [C('قرار بعد التجربة', 'Post-pilot decision', 'المضي بعد تحقق الترخيص ونسبة إتمام مقبولة تعاقديًا ومساهمة موجبة لكل مسار وحجم يغطي التعادل ضمن الطاقة.', 'Proceed after licensing is confirmed, completion meets the contractual standard, routes contribute positively and volume covers break-even within capacity.'), C('التوسع المرحلي', 'Phased expansion', 'تُضاف منطقة واحدة بعد أربعة أسابيع مستقرة. يُؤجل التوسع إذا احتاجت التوصيلات دعمًا دائمًا غير محسوب أو بقي التحصيل متأخرًا.', 'Add one area after four stable weeks. Defer if routes depend on unbudgeted support or collections remain late.')],
    brand: [C('وعد المتابعة', 'Tracking promise', 'يصبح الوعد حالة دقيقة وخطوة تالية وموعد تحديث، لا ادعاء توصيل فوري لكل منطقة.', 'The promise becomes accurate status, a next step and an update time, rather than instant delivery everywhere.'), C('تطبيقات التشغيل', 'Operating applications', 'الأولوية لملصق الطرد وشاشة الحالات وإشعارات التعثر وإثبات التسليم وهوية المركبة، بألوان لا تخفي معنى الحالة.', 'Prioritize parcel labels, status screens, exception notices, delivery proof and vehicle graphics, using color without obscuring status meaning.')],
    sources: [method, vat, { title: L('الهيئة العامة للنقل — الأنظمة والخدمات', 'Transport General Authority — Regulations and services'), url: 'https://www.tga.gov.sa/', purpose: L('جهة مرجعية لحسم تصنيف نقل الطرود والتوصيل ومتطلبات الترخيص؛ لا يستند تقدير الرواتب أو التسعير إلى هذا المصدر.', 'Authority for confirming parcel/delivery classification and licensing; payroll and prices are not derived from this source.') }],
  },
  {
    slug: 'dahsha', name: L('دهشة', 'DAHSHA'), sector: L('متجر ألعاب مع بيع رقمي', 'Toy store with digital sales'), hero: '/assets/studies/dahsha/campaign.webp', theme: { ink: '#191B2A', paper: '#FFF8E7', soft: '#E6ECFF' }, model: toysModel,
    summary: L('هل يحقق متجر ألعاب مختار بعناية مبيعات تغطي المكان والمخزون، مع تجربة تساعد الأسرة على اختيار مناسب؟', 'Can a curated toy store cover its premises and inventory while helping families make a suitable choice?'),
    scope: L('متجر تصوري واحد لألعاب الفئة العمرية من أربع إلى عشر سنوات، مع طلب إلكتروني واستلام أو توصيل. ليس مركز ترفيه أو حضانة، ولا يشمل تصنيع الألعاب أو بيعها بالجملة.', 'One concept store for toys aimed at ages four to ten, with online ordering, pickup or delivery. It is not an amusement center or nursery; manufacturing and wholesale are excluded.'),
    decision: L('يبدأ القرار باختبار السلة ودوران المخزون وسلامة التوريد. لا يكفي ارتفاع الطلب في موسم هدايا واحد لتبرير إيجار وتشكيلة ثابتين طوال العام.', 'Start by testing baskets, stock turnover and safe sourcing. One gift-season peak cannot justify year-round rent and assortment commitments.'),
    market: [C('المشتري والمستخدم', 'Buyer and user', 'الأسرة تشتري والطفل يستخدم. نختبر وضوح العمر والمهارة وطريقة اللعب، مع عدم تحويل الوصف إلى ادعاء تربوي غير موثق.', 'The family buys and the child uses the product. Test clarity of age suitability, skills and play instructions without making unsupported educational claims.'), C('المنافسة', 'Competition', 'البدائل متجر كبير أو منصة أسعار أو متجر متخصص. المقارنة تشمل توفر المنتج وسلامة المعلومات وإمكانية التجربة وخدمة ما بعد البيع، إلى جانب السعر.', 'Alternatives include large retailers, price-focused marketplaces and specialists. Compare availability, reliable information, trials and after-sales support as well as price.'), C('الطلب والموسمية', 'Demand and seasonality', 'تُفصل مشتريات الهدية عن الاستخدام اليومي. لا توجد بيانات مبيعات فعلية في المثال؛ تدرج السنة لا يحاكي الإجازات أو العيد أو العودة للمدارس.', 'Separate gift purchases from everyday use. The example contains no observed sales; its ramp does not simulate holidays, Eid or back-to-school peaks.')],
    validation: [C('متجر مؤقت', 'Pop-up test', 'تجربة بيع لمدة أسبوعين بتشكيلة صغيرة. يسجل مدير المتجر عدد الزوار والتحويل والسلة والمرتجعات بحسب الفئة والعمر.', 'Run a two-week pop-up with a narrow assortment. Record visitors, conversion, baskets and returns by category and age group.'), C('تدقيق التوريد', 'Supply review', 'الحصول على عروض ووثائق مطابقة ومعلومات عمر وتحذيرات لكل صنف. مقارنة شروط إرجاع الراكد وحد الطلب وموعد إعادة التوريد.', 'Obtain quotations, conformity documents, age information and warnings for each SKU. Compare slow-stock returns, minimum orders and replenishment lead times.')],
    offer: [C('تشكيلة البداية', 'Initial assortment', 'ألعاب بناء وخيال ومهارة ضمن فئات واضحة ومخزون محدود لكل صنف. تنوع التجربة أهم من شراء عمق كبير قبل معرفة الطلب.', 'Construction, imaginative and skill-based toys in clear categories, with limited depth per SKU. Test variety before committing to deep stock.'), C('مصادر الإيراد', 'Revenue sources', 'بيع الألعاب وباقات الهدايا؛ لا يدخل الأساس تذاكر فعاليات أو اشتراكات. متوسط الفاتورة مستبعدة منه الضريبة والخصومات محسوبة ضمنه.', 'Toy and gift-bundle sales; tickets and subscriptions are excluded. The average transaction is net of VAT and already reflects discounts.'), C('القناة الرقمية', 'Digital channel', 'المخزون نفسه يخدم المتجر والطلبات الرقمية مع تحديث الكمية. تكلفة تجهيز وشحن الطلب الرقمي ضمن النسبة المتغيرة الموزونة.', 'One inventory serves store and online orders with quantity updates. Online packing and shipping are included in the blended variable-cost share.')],
    operations: [C('سلامة المنتج', 'Product safety', 'لا يدخل الصنف قبل مراجعة وثائقه وملصق العمر والتحذيرات. تُحفظ بيانات المورد والدفعة وآلية سحب المنتج عند الحاجة.', 'Review documentation, age labeling and warnings before accepting a SKU. Retain supplier and batch information and a product recall process.'), C('الفريق وتجربة المتجر', 'Team and store experience', 'الفريق يساعد الأسرة ويدير عرضًا تجريبيًا محدودًا تحت إشراف مناسب. لا تُفترض خدمة رعاية أطفال أو ترك الطفل داخل المتجر.', 'The team assists families and manages limited supervised demonstrations. Childcare or leaving children in the store is not assumed.'), C('إدارة المخزون', 'Inventory management', 'جرد دوري وتقسيم سريع وبطيء الحركة ونقطة إعادة طلب. تتوقف زيادة شراء صنف عندما ترتفع مدة بقائه، حتى لو كانت هويته جذابة.', 'Use cycle counts, fast/slow classification and reorder points. Stop increasing a slow seller even when its presentation is attractive.')],
    capacityNote: L('السقف الافتراضي ألف وخمسمئة فاتورة شهريًا بموارد البداية. يقاس ازدحام المواسم وسرعة الخدمة عمليًا؛ مبيعات أكبر قد تحتاج فريقًا ومخزونًا ومساحة إضافية.', 'Assumed capacity is fifteen hundred monthly transactions with initial resources. Test seasonal congestion and service speed; higher sales may need additional staff, stock and space.'),
    collectionNote: L('التحصيل والسداد في الشهر نفسه، والمخزون الختامي ثابت بتكلفة الشراء بعد تجديد ما بيع. شراء الموسم مبكرًا وتخفيض الراكد ليسا ممثلين زمنيًا؛ يلزم لهما جدول أصناف ومشتريات.', 'Collection and payment occur in the same month, with closing stock constant at purchase cost after replenishment. Early seasonal buying and slow-stock markdown timing require a separate SKU and purchasing schedule.'),
    assumptions: [C('السلة والتحويل', 'Basket and conversion', 'الألف فاتورة والسعر افتراض اختبار. يستبدلهما مدير المتجر بفواتير التجربة وعد زوار موثق، ثم يراجع التغير بين الموسم والأشهر العادية.', 'The thousand transactions and price are test assumptions. Replace them with pilot receipts and documented footfall, then compare seasonal and normal months.'), C('المخزون والإيجار', 'Stock and rent', 'مبالغ التأسيس والمخزون تقديرات تحتاج عروضًا للموقع والأصناف والحد الأدنى. وديعة الإيجار مبلغ مجمد وليست مصروفًا شهريًا.', 'Setup and stock estimates need site and SKU quotations with minimum orders. The rental deposit is tied-up cash, not a monthly expense.')],
    variableCosts: L('مزيج افتراضي: خمسون بالمئة تكلفة شراء الألعاب، وثلاثة دفع وتغليف، وثلاثة تنفيذ وتوصيل موزون، واثنان تلف ومرتجعات. التسويق الثابت ورواتب المتجر ضمن الثابت.', 'Assumed mix: fifty percent merchandise purchases, three payment and packing, three blended fulfillment and delivery, and two damage and returns. Baseline marketing and store payroll are fixed.'), tax: netTax,
    risks: [C('السلامة والمرتجعات', 'Safety and returns', 'المؤشر: معلومات ناقصة أو شكوى سلامة. الإجراء: حجز الصنف وتتبعه والرجوع إلى المورد والجهة المختصة قبل استئناف بيعه.', 'Signal: missing information or a safety complaint. Response: quarantine and trace the SKU, consulting the supplier and relevant authority before resuming sales.'), C('الإيجار والموسم', 'Rent and seasonality', 'المؤشر: تعادل أعلى من تحويل الموقع أو فائض موسمي يخفي خسارة عادية. الإجراء: اختبار مؤقت أولًا وتحليل سنة ومخزون، لا أسبوع مبيعات فقط.', 'Signal: break-even exceeds site conversion or seasonal gains mask ordinary losses. Response: pilot first and examine a full year and inventory, not one sales week.')],
    gates: [C('التحقق قبل الإيجار', 'Before signing a lease', 'خلال ستة أسابيع: تدقيق موردين، اختبار بيع، عد حركة موقع، ثم عرض تجهيز وإيجار. لا يُعتمد موقع قبل إثبات طلب محتمل يغطي التعادل.', 'Over six weeks: review suppliers, test sales, count site traffic, then obtain fit-out and rent offers. Approve a site only after plausible demand supports break-even.'), C('المضي أو تعديل النطاق', 'Proceed or resize', 'المضي بعد قبول مستندات الأصناف ومساهمة موجبة وخطة تمويل مخزون الموسم. تُصغّر المساحة أو التشكيلة إن استهلكت السيولة قبل استقرار الطلب.', 'Proceed with acceptable SKU documentation, positive contribution and seasonal stock funding. Reduce space or assortment if cash runs out before demand stabilizes.')],
    brand: [C('الدهشة مع الوضوح', 'Wonder with clarity', 'تدعم الهوية فضول الطفل، بينما توضح للأسرة العمر والمحتوى وطريقة الاستخدام والتحذيرات بترتيب بصري ثابت.', 'Support children’s curiosity while giving families a consistent hierarchy for age, contents, use and warnings.'), C('أولويات الإطلاق', 'Launch priorities', 'بطاقة رف، صفحة منتج، تغليف هدية، إيصال وسياسة استبدال. لا تحجب الرسومات المرحة معلومات السلامة.', 'Prioritize shelf labels, product pages, gift packaging, receipts and return terms. Playful graphics must keep safety information visible.')],
    sources: [method, vat, { title: L('المواصفات السعودية — اللائحة الخليجية للعب الأطفال', 'SASO — Gulf technical regulation for children’s toys'), url: 'https://saso.gov.sa/ar/laws-and-regulations/technical_regulations/pages/regulation1.aspx', purpose: L('مرجع سلامة ومطابقة يستلزم مراجعة وثائق كل صنف؛ لا يعني أن الأصناف التصورية معتمدة.', 'Safety and conformity reference requiring SKU-specific documentation review; concept products are not represented as certified.') }],
  },
  {
    slug: 'nabra', name: L('نبرأ', 'NABRA'), sector: L('رعاية طبية خارجية', 'Outpatient medical care'), hero: '/assets/nabra/campaign.webp', theme: { ink: '#143B3A', paper: '#F2F0E7', soft: '#DCE8DF' }, model: medicalModel,
    summary: L('هل يمكن تشغيل رعاية خارجية واضحة وقريبة من المراجع، بطاقة وفريق يحققان الجودة ويغطيان التكلفة؟', 'Can accessible, clear outpatient care be delivered with staffing and capacity that sustain quality and cover costs?'),
    scope: L('مركز طبي تصوري بنطاق استشارات وفحص خارجي أولي؛ لا تنويم أو جراحة أو مختبر إنتاجي أو طوارئ مستشفى في النموذج. التصنيف النظامي وعدد التخصصات والغرف يُحسم قبل اعتماد الموقع والميزانية.', 'A concept center for consultations and initial outpatient examinations. Inpatient care, surgery, laboratory production and hospital emergency services are excluded. Confirm the legal facility category, specialties and rooms before approving premises and budget.'),
    decision: L('ترتيب القرار: صلاحية نطاق الترخيص والموقع، ثم نموذج الكادر والطاقة، ثم طلب مدفوع قابل للتحقق وتمويل فترة الوصول للتعادل. لا تبرر الإيرادات المفترضة تخفيض متطلبات الرعاية.', 'Decision order: validate licensing scope and premises, then staffing and capacity, then evidenced paid demand and ramp-up funding. Assumed revenue does not justify reducing care requirements.'),
    market: [C('المراجع والخدمة', 'Patient and service', 'مراجع يحتاج استشارة خارجية ومعلومة واضحة عن الموعد والتكلفة والخطوة التالية. تُحصر الخدمات المناسبة للنطاق بدل افتراض علاج جميع الحالات.', 'A patient seeking outpatient consultation with clear appointment, cost and next-step information. Define services appropriate to the scope rather than assuming all conditions can be treated.'), C('البدائل', 'Alternatives', 'مجمع قريب أو عيادة متخصصة أو منشأة مغطاة تأمينيًا. تقارن الدراسة الوصول والمواعيد والخدمات والتغطية والتكلفة المعلنة دون تقييم جودة طبية غير موثق.', 'Alternatives include nearby centers, specialist clinics and insured providers. Compare access, appointments, scope, coverage and stated prices without unsupported clinical-quality rankings.'), C('الطلب المدفوع', 'Paid demand', 'الحاسبة تعد الزيارات المدفوعة وليست عدد المرضى الفريدين. تكرار الزيارة والإلغاء وعدم الحضور والإحالة قد يغير الحجم والسلة.', 'The calculator counts paid visits, not unique patients. Repeat visits, cancellations, non-attendance and referrals can change volume and average revenue.')],
    validation: [C('مسح نطاق الخدمة', 'Catchment review', 'حصر مقدمي الخدمة ومواعيدهم وأسعارهم المعلنة ومقابلة عشرين شخصًا عن صعوبات الوصول؛ دون جمع تشخيصات أو معلومات صحية شخصية.', 'Map providers, appointments and published fees, then interview twenty people about access difficulties without collecting diagnoses or personal health information.'), C('مراجعة تشغيل متخصصة', 'Specialist operating review', 'يعتمد مسؤول طبي مختص قائمة الخدمات والغرف والكوادر والمعدات ومسارات الإحالة. تجمع عروض الموقع والتجهيز والتأمين والأنظمة قبل اعتماد الأرقام.', 'A qualified clinical lead reviews services, rooms, staffing, equipment and referral pathways. Obtain premises, fit-out, insurance and system quotes before approving figures.')],
    offer: [C('الإيراد الأساسي', 'Base revenue', 'زيارة استشارية مدفوعة بمتوسط صافي إيراد معلن في النموذج، مع فحص ضمن النطاق. لا توجد إيرادات مفترضة من تحاليل خارجية أو وصف دواء أو إحالات.', 'A paid consultation with the modeled average net revenue and examination within scope. No revenue is assumed from external tests, prescriptions or referrals.'), C('الدفع والتأمين', 'Payment and insurance', 'الأساس دفع مباشر. إضافة عقود تأمين تتطلب أسعارًا وموافقات ورفض مطالبات وجدول تحصيل منفصلًا؛ تغيير التأخر وحده اختبار سيولة وليس نموذج تأمين كاملًا.', 'The base uses direct payment. Insurance contracts need tariffs, authorizations, rejected claims and a separate collection schedule; changing the lag alone is a cash stress test, not a full insurance model.'), C('تسعير واضح', 'Clear pricing', 'توضح الرسوم وما يدخل في الزيارة قبل الحجز، مع سياسة مراجعة وإلغاء معتمدة. لا يُعد تقديم إجراءات إضافية شرطًا لبلوغ الإيراد المفترض.', 'Explain fees and included services before booking, with approved follow-up and cancellation terms. Additional procedures are not assumed necessary to meet modeled revenue.')],
    operations: [C('رحلة المراجع', 'Patient journey', 'حجز وتأكيد واستقبال وتحقق هوية ثم مقابلة وتوضيح الخطوة التالية. يفصل المسار الإداري عن القرار السريري ويحفظ خصوصية المراجع.', 'Booking, confirmation, reception, identity checks, consultation and next-step explanation. Separate administration from clinical decisions and protect patient privacy.'), C('الفريق والسلامة', 'Team and safety', 'الكادر الطبي والتمريضي وخدمة الاستقبال يعملون ضمن نطاق معتمد. تُراجع مكافحة العدوى والنفايات والصيانة والإحالة والتغطية عند الغياب مع مختص.', 'Clinical, nursing and reception staff work within approved scope. Specialists review infection control, waste, maintenance, referrals and absence coverage.'), C('الترخيص قبل التشغيل', 'Licensing before operation', 'وزارة الصحة توفر مسارات تراخيص المنشآت والممارسين عبر صحة. تُحدد المتطلبات الفعلية بحسب التصنيف والتخصص؛ أسماء العلامة وصور الهوية ليست دليل ترخيص.', 'MOH provides facility and practitioner licensing services through Seha. Actual requirements depend on classification and specialty; the brand name and identity images are not evidence of licensing.')],
    capacityNote: L('سقف تخطيطي ألف زيارة مدفوعة شهريًا؛ افتراض غرفتي فحص وعشرين موعدًا لكل غرفة في ستة وعشرين يومًا يعطي ألفًا وأربعين خانة قبل الخصومات التشغيلية. يعتمد المختص زمن الزيارة والتغطية قبل قبول هذا السقف.', 'Planning ceiling: one thousand paid visits monthly. Two rooms with twenty appointments each across twenty-six days provide one thousand forty slots before operating allowances. A specialist must validate visit time and coverage.'),
    collectionNote: L('الأساس تحصيل مباشر في شهر الزيارة مع دفع التكاليف في شهرها. لا يشمل تأخر سداد جهة ضامنة أو مطالبة ضريبية أو رفض مطالبة تأمين؛ تُضاف مساراتها عند اختيار مزيج الدافعين.', 'The base collects in the visit month and pays costs in the same month. Delayed payer settlements, tax claims and insurance rejections are excluded and require schedules once the payer mix is chosen.'),
    assumptions: [C('الزيارات والإيراد', 'Visits and revenue', 'عدد الزيارات ومتوسطها المالي افتراضان بلا تشغيل فعلي. يحل محلهما تحليل وصول وموعد وسعر معلن وعقود دفع بعد حسم التخصص.', 'Visit count and average revenue are assumptions without operating evidence. Replace them with access, appointment and published-price analysis and payer agreements after choosing specialties.'), C('ميزانية النطاق الطبي', 'Clinical scope budget', 'الأجور والتجهيز والمخصصات ليست عروضًا ولا رسومًا رسمية. يُعاد بناؤها بعد اعتماد الكادر والموقع والمعدات والتزامات التشغيل.', 'Payroll, fit-out and allowances are neither quotations nor official fee schedules. Rebuild them after staffing, premises, equipment and operating obligations are established.')],
    variableCosts: L('نسبة افتراضية من الإيراد: عشرة بالمئة مستهلكات مرتبطة بالزيارة، وخمسة خدمات تشغيلية خارجية ضمن النطاق، وثلاثة دفع واستهلاك إضافي. الرواتب الأساسية ثابتة ولا تتكرر هنا.', 'Assumed revenue shares: ten percent visit consumables, five external operating services within scope and three payment and incremental usage costs. Core payroll is fixed and not duplicated here.'),
    tax: L('متوسط الزيارة هو إيراد المنشأة دون القيمة المضافة، وليس السعر النهائي لكل مراجع. لا تُطبق الحاسبة نسبة موحدة على جميع المرضى؛ تُراجع المعالجة ومزيج الدافعين وأي تحمل حكومي مستحق مع مختص، ويُضاف توقيت التحصيل الضريبي منفصلًا.', 'The visit input is facility revenue excluding VAT, not every patient’s final price. The calculator applies no blanket rate to all patients. Review treatment, payer mix and any eligible government-borne VAT with a specialist, and model tax-related collections separately.'),
    risks: [C('نطاق غير قابل للترخيص', 'Unlicensable scope', 'المؤشر: تعارض الموقع أو الكادر مع التصنيف. الإجراء: إيقاف الالتزام بالتجهيز حتى اعتماد المتطلبات وإعادة الميزانية.', 'Signal: premises or staffing do not fit the facility category. Response: pause fit-out commitments until requirements are established and the budget revised.'), C('تدرج أبطأ من المتوقع', 'Slower ramp-up', 'المؤشر: إشغال منخفض أو إلغاءات مرتفعة مع أجور كاملة. الإجراء: مراجعة الوصول والمواعيد والنطاق والاحتياطي، دون تقديم خدمة خارج القدرة.', 'Signal: low utilization or high cancellations while full payroll continues. Response: review access, appointments, scope and reserve without offering care beyond capacity.')],
    gates: [C('بوابة ما قبل التأسيس', 'Pre-setup gate', 'تثبيت التصنيف والموقع والتخصص والتراخيص المطلوبة ثم عروض الكادر والتجهيز. مدة التجهيز تعتمد على هذه المتطلبات، وليست موعد افتتاح مضمونًا.', 'Confirm category, premises, specialty and required licences, then staffing and fit-out quotations. Setup duration depends on those requirements, not a guaranteed opening date.'), C('بوابة المضي', 'Proceed gate', 'طلب قابل للتحقق يتجاوز التعادل داخل الطاقة، وتغطية فجوة النقد، وخطة تشغيل يقرها مختص. يُعدل النطاق أو يؤجل القرار عند فشل أحد الشروط.', 'Evidence of demand above break-even within capacity, funded cash gaps and a specialist-reviewed operating plan. Revise scope or defer when a condition fails.')],
    brand: [C('المرافقة والوضوح', 'Support and clarity', 'يربط نموذج التشغيل وعد «معك، خطوة بخطوة» بإشعار الموعد والإرشاد والتكلفة والخطوة التالية، دون وعود شفاء أو نتائج مضمونة.', 'Connect “With you, step by step” to appointment notices, wayfinding, cost and next steps, without cure promises or guaranteed outcomes.'), C('ترتيب التطبيقات', 'Application order', 'الأولوية للحجز والاستقبال والإرشاد ونماذج المعلومات والخصوصية؛ ثم الإعلان بعد جاهزية الخدمة والتراخيص.', 'Prioritize booking, reception, wayfinding, information forms and privacy; advertise after service readiness and licensing.')],
    sources: [method, vat, { title: L('وزارة الصحة — خدمات التراخيص الطبية', 'MOH — Medical licensing services'), url: 'https://www.moh.gov.sa/eservices/licences/pages/default.aspx', purpose: L('مرجع لمسارات ترخيص المنشأة والممارسين؛ ليس تقديرًا للرسوم أو مدة جاهزية المركز.', 'Reference for facility and practitioner licensing services, not a fee estimate or center readiness timetable.') }],
  },
  {
    slug: 'wizan', name: L('وِزان', 'WIZAN'), sector: L('منصة عافية باشتراك شهري', 'Subscription wellbeing platform'), hero: '/assets/studies/wizan/mark-v2.webp', theme: { ink: '#0F1F1D', paper: '#F2EFE7', soft: '#CCD7D0' }, model: wizanModel,
    summary: L('هل يحتفظ المستخدم باشتراك عافية يساعده على عادات مستمرة، وهل تغطي مساهمته تكلفة الخدمة واكتسابه؟', 'Will users retain a wellbeing subscription that supports sustainable habits, and will their contribution cover service and acquisition costs?'),
    scope: L('منصة تصورية لمحتوى وعادات ومتابعة ذاتية عامة باشتراك أفراد. لا تشخيص أو وصف علاجي أو استشارات طبية أو أجهزة طبية في النموذج. لا توجد أعداد مستخدمين فعلية أو نتائج صحية مثبتة.', 'A concept platform for general content, habits and self-tracking with individual subscriptions. Diagnosis, treatment, medical consultations and medical devices are excluded. No actual user counts or proven health outcomes are asserted.'),
    decision: L('الاستمرار يعتمد على الاحتفاظ المدفوع لا التنزيلات. تُختبر دفعة صغيرة وتُراجع أسباب الإلغاء قبل زيادة الاكتساب، لأن نموًا سريعًا بتسرّب مرتفع قد يستهلك النقد.', 'Continuation depends on paid retention, not downloads. Test a small cohort and cancellation reasons before scaling acquisition; rapid growth with high churn can consume cash.'),
    market: [C('شريحة البداية', 'Initial segment', 'بالغ يريد عادة يومية بسيطة وشرحًا مفهومًا لمؤشرات عامة، دون احتياج لخدمة طبية. تُحدد عادة واحدة ومشكلة متابعة واحدة في النسخة الأولى.', 'An adult seeking a simple daily habit and understandable general indicators, without a medical service need. The first release focuses on one habit and one tracking problem.'), C('البدائل', 'Alternatives', 'محتوى مجاني أو تطبيق عادات أو برنامج عافية موظفين. نختبر سبب الدفع بعد التجربة، وما إذا كانت المتابعة توفر قيمة مستمرة.', 'Alternatives include free content, habit apps and employer wellbeing programs. Test the reason to pay after trial and whether follow-up creates lasting value.'), C('السوق القابل للخدمة', 'Serviceable demand', 'يبدأ من مستخدمين مؤهلين يتحولون إلى اشتراك مدفوع ويجددونه. التنزيل والتسجيل المجاني لا يدخلان الإيراد، ولا نفترض حجم سوق منشورًا.', 'Start from qualified users who convert to paid subscriptions and renew. Downloads and free signups do not generate modeled revenue; no published market size is assumed.')],
    validation: [C('تجربة احتفاظ', 'Retention pilot', 'دفعة مدفوعة محدودة ومتابعة لثلاث دورات شهرية. يسجل مسؤول المنتج التفعيل والتجديد والإلغاء والدعم، مع مقابلات اختيارية عن تجربة المنتج.', 'Run a small paid cohort through three monthly cycles. Track activation, renewal, cancellation and support, with optional product-experience interviews.'), C('اختبار اكتساب', 'Acquisition test', 'ميزانية قناة محدودة تقيس تكلفة المشترك الذي دفع فعلًا، مع فصل العملاء العائدين والإحالات عن الاكتساب الجديد.', 'Use a limited channel budget to measure cost per actually paying subscriber, separating returning customers and referrals from new acquisition.')],
    offer: [C('قيمة الاشتراك', 'Subscription value', 'محتوى منظم وخطة عادة ومتابعة تقدم ذاتي وتذكيرات اختيارية. لا يعتمد الوعد على نتيجة صحية محددة أو تفسير طبي آلي.', 'Structured content, a habit plan, self-reported progress and optional reminders. The promise does not depend on a specific health outcome or automated medical interpretation.'), C('شروط الدفع', 'Billing terms', 'اشتراك شهري قابل للإلغاء؛ يفترض النموذج دورة شهرية واحدة دون دفعات سنوية أو فترات مجانية. توضح سياسة الاسترداد قبل التجربة المدفوعة.', 'A cancellable monthly subscription. The model uses one monthly cycle without annual prepayments or free periods. Explain refund terms before the paid pilot.'), C('مصادر مستقبلية', 'Future sources', 'اشتراكات الشركات أو الشراكات ليست ضمن الأساس. إضافتها تتطلب تكلفة بيع وعقد وخصوصية وطريقة فوترة مستقلة.', 'Corporate subscriptions and partnerships are outside the base. They need separate sales costs, contracts, privacy treatment and billing.')],
    operations: [C('نظام المنتج', 'Product system', 'تسجيل بسيط ثم اختيار عادة ثم متابعة وتذكير وتجديد أو إلغاء واضح. تُراجع جودة المحتوى وإمكانية الوصول قبل إضافة مزايا جديدة.', 'Simple signup, habit selection, follow-up, reminders and clear renewal or cancellation. Review content quality and accessibility before adding features.'), C('الفريق والخدمة', 'Team and service', 'إدارة منتج وصيانة تقنية ومحتوى ودعم أساسي. تكلفة المستخدم المتغيرة تغطي خدمة إضافية ودفعًا وبنية تشغيل؛ لا يُعاد احتساب الفريق الثابت.', 'Product management, maintenance, content and baseline support. Per-user variable cost covers incremental service, payment and infrastructure without duplicating fixed staffing.'), C('الخصوصية', 'Privacy', 'تبدأ النسخة بأقل بيانات لازمة وبإفصاح مفهوم وخيارات تحكم. تُراجع الغاية والأساس النظامي والحذف والأمن مع مختص قبل جمع معلومات حساسة.', 'Start with minimal necessary data, understandable notices and user controls. Review purpose, lawful basis, deletion and security with a specialist before collecting sensitive information.')],
    capacityNote: L('الطاقة المفترضة ألفا مشترك نشط بهذا الدعم والبنية. لا نوقف الحساب آليًا عند تجاوزها؛ تظهر ملاحظة لأن النمو حينها يحتاج ميزانية جديدة. الأعداد الكسرية توقع إحصائي لدفعات المشتركين وليست أشخاصًا جزئيين.', 'Assumed support and infrastructure capacity is two thousand active subscribers. The calculation is not artificially capped; it flags growth beyond capacity as requiring a new budget. Fractional users are cohort expectations, not partial people.'),
    collectionNote: L('في بداية كل شهر يتسرّب جزء من المشتركين السابقين، ثم ينضم المشتركون الجدد، ويُفوتر الجميع لدورة كاملة. التحصيل والتكاليف في الشهر نفسه؛ لا يوجد توزيع يومي أو دفعات سنوية. تكلفة اكتساب مشترك التجربة الأولية ضمن التأسيس.', 'At each month’s start, some previous subscribers churn, then new subscribers join; all remaining users are billed for a full cycle. Collections and costs occur in that month, without daily proration or annual prepayments. Initial pilot acquisition is in setup.'),
    assumptions: [C('الاحتفاظ والاكتساب', 'Retention and acquisition', 'البداية والمشتركون الجدد والتسرّب افتراضات، لا بيانات منصة قائمة. يستبدلها مسؤول المنتج بنتائج دفعات مدفوعة بعد ثلاث دورات على الأقل.', 'Starting users, new users and churn are assumptions, not live-platform data. Replace them with paid-cohort results after at least three cycles.'), C('تكلفة الخدمة', 'Service cost', 'تقدير تكلفة المشترك يشمل موارد تشغيل ودفع ودعم متزايدة؛ تُقاس من الاستخدام والفواتير. تكلفة الاكتساب منفصلة عن الثابت لمنع تكرارها.', 'Per-user costs estimate incremental infrastructure, payment and support, to be measured from usage and invoices. Acquisition is separate from fixed cost to prevent double counting.')],
    variableCosts: L('عشرة ريالات لخدمة المشترك النشط في الشهر، ومئة ريال لكل مشترك جديد في الأساس. الأجر والإنتاج المستمر للمحتوى ضمن الثابت. النفقات لا تتوقف لمجرد تسرّب مستخدمين.', 'The base assumes ten SAR per active subscriber per month and one hundred SAR per new subscriber acquired. Payroll and ongoing content production are fixed. Those expenses continue when users churn.'), tax: netTax,
    risks: [C('تسرّب مرتفع', 'High churn', 'المؤشر: نمو التسجيل مع ضعف التجديد. الإجراء: مراجعة التفعيل والقيمة وأسباب الإلغاء، وإبطاء الإنفاق على الاكتساب قبل علاج الاحتفاظ.', 'Signal: signups grow while renewals weaken. Response: review activation, value and cancellation reasons; slow acquisition spend until retention improves.'), C('توسع طبي أو بيانات زائد', 'Medical scope or excessive data', 'المؤشر: ميزة تفسر حالة صحية أو تجمع بيانات بلا ضرورة. الإجراء: إعادة تحديد النطاق ومراجعة تخصصية قبل النشر أو الجمع.', 'Signal: a feature interprets a health condition or collects unnecessary data. Response: redefine scope and obtain specialist review before release or collection.')],
    gates: [C('خطة التحقق', 'Validation plan', 'شهر لتحديد الحاجة والنسخة والخصوصية، ثم ثلاثة أشهر لدفعة مدفوعة. تُراجع البيانات شهريًا ويُوثق الفرق بين إلغاء طوعي وفشل دفع.', 'One month to define the need, product and privacy, then three months for a paid cohort. Review monthly and distinguish voluntary cancellation from payment failure.'), C('شرط التوسع', 'Expansion condition', 'تجديد متكرر ومساهمة موجبة بعد خدمة المستخدم واكتسابه، وتمويل يكفي فترة الوصول لتعادل المشتركين. يؤجل التوسع إذا كان النمو يفاقم العجز.', 'Require repeat renewals, positive contribution after service and acquisition, and cash through subscriber break-even. Defer expansion if growth worsens the deficit.')],
    brand: [C('اتزان الوعد', 'A measured promise', 'تترجم وِزان المؤشر إلى معنى وخطوة صغيرة قابلة للاستمرار. تعكس اللغة حدود الخدمة وتبتعد عن التخويف أو الوعد العلاجي.', 'WIZAN turns an indicator into meaning and a small sustainable step. Language reflects service boundaries and avoids fear or treatment promises.'), C('تطبيقات الثقة', 'Trust applications', 'الأولوية للتفعيل ولوحة المتابعة والتذكير الاختياري وصفحة السعر والإلغاء والخصوصية، مع حالات تقدم مفهومة بعيدًا عن الضغط.', 'Prioritize onboarding, progress, optional reminders, pricing, cancellation and privacy, with understandable progress states and no pressure.')],
    sources: [method, vat, privacy],
  },
  {
    slug: 'rahb-aldar', name: L('رَحْب الدار', 'RAHB ALDAR'), sector: L('تطوير وبيع وحدات سكنية', 'Residential development and sales'), hero: '/assets/studies/rahb-aldar/hero.webp', theme: { ink: '#172F3D', paper: '#F1F0E8', soft: '#BBC6DD' }, model: propertyModel,
    summary: L('هل يغطي بيع مشروع سكني محدود تكلفة الأرض والتطوير والمخاطر، وهل يتوفر التمويل قبل بدء التحصيل؟', 'Will a small residential development’s sales cover land, development and risk costs, and is funding available before collections start?'),
    scope: L('مشروع تصوري من عشر وحدات، يُبنى كاملًا ثم تُتم مبيعاته على ست دفعات شهرية بعد الشهر الثامن عشر. ليس مشروعًا قائمًا أو أرضًا محددة، ولا يفترض بيعًا على الخارطة أو ودائع مشترين أو قرضًا معتمدًا.', 'A concept ten-unit project built in full, with sales closing across six months after month eighteen. No actual project or specific plot, off-plan sales, buyer deposits or approved loan is assumed.'),
    decision: L('القرار يتوقف على صلاحية الأرض والتكلفة المعتمدة وقدرة السوق على استيعاب الوحدات، مع تمويل أكبر عجز قبل التحصيل. فائض المشروع في نهايته لا يعالج نقص تمويل البناء.', 'The decision depends on site suitability, verified cost and market absorption, with funding for the peak pre-collection deficit. A final project surplus does not solve a construction funding gap.'),
    market: [C('المشتري', 'Buyer', 'أسرة تبحث عن وحدة سكنية واضحة المساحة والخصوصية والضوء وتكلفة التملك. تُحدد المدينة والحي ونوع الوحدة قبل اعتبار السعر قابلًا للتحقق.', 'A household seeking clear space, privacy, daylight and ownership costs. Define city, neighborhood and unit type before treating price as verifiable.'), C('المقارنات', 'Comparables', 'نقارن وحدات قريبة في الموقع والمساحة والعمر والمواقف والخدمات، ونفصل سعر العرض عن صفقة أتمت البيع. لا توجد صفقات مقارنة موثقة في هذا المثال.', 'Compare nearby units by location, area, age, parking and services, separating asking prices from completed transactions. This example includes no verified comparable transactions.'), C('الاستيعاب', 'Absorption', 'توقع البيع مبني على عدد وحدات قد يقبلها السوق خلال الأفق. الوحدات غير المباعة لا تتحول إلى تحصيل أو قيمة نهائية مفترضة.', 'Sales depend on units the market may absorb within the horizon. Unsold units do not become cash collections or assumed terminal value.')],
    validation: [C('الأرض والنطاق', 'Land and scope', 'فحص الملكية والتنظيم والارتدادات والخدمات والتربة وقابلية الترخيص عبر المختصين والجهات ذات الصلة قبل التزام الشراء.', 'Specialists and relevant authorities review title, zoning, setbacks, utilities, soil and permit feasibility before purchase commitment.'), C('السعر والتكلفة', 'Price and cost', 'حصر صفقات مقارنة متاحة وعروض منافسين ومقابلات مشترين، ثم حصر كميات وثلاثة عروض مقاولين متجانسة النطاق وجدول صرف.', 'Review available completed comparables, competing offers and buyer interviews, then obtain a quantity survey, three like-for-like contractor quotes and a payment schedule.')],
    offer: [C('المنتج السكني', 'Residential product', 'وحدات محددة بمساحات وتشطيب ومواقف وخدمات واضحة؛ السعر في الحاسبة متوسط للوحدة، ويُستبدل بمصفوفة أسعار إذا اختلفت المساحات.', 'Units with defined areas, specifications, parking and services. The calculator uses an average unit price; replace it with a pricing matrix when areas vary.'), C('الإيراد', 'Revenue', 'إتمام البيع بعد البناء والتحصيل عند الإتمام. لا دخل إيجاري ولا إيراد حجوزات أو بيع أرض متبقٍ في الأساس.', 'Sales close after construction and are collected at closing. No rent, reservation revenue or residual land sales are assumed.'), C('تكلفة البيع', 'Selling costs', 'نسبة مستقلة للتسويق والوساطة والإتمام من الإيرادات المحققة. لا تُخصم من سعر الوحدة مرتين، ولا تُستخدم بدل مخصص الضرائب.', 'A separate share of realized revenue covers marketing, brokerage and closing. It is not deducted twice from unit price or substituted for tax allowance.')],
    operations: [C('قبل البناء', 'Before construction', 'الأرض والضرائب المفترضة في الشهر الأول، والتصميم والإشراف والتراخيص موزعة على الأشهر الستة الأولى. المدد تخطيطية تحتاج برنامجًا فنيًا.', 'Land and the assumed tax allowance are paid in month one; design, supervision and permits are spread across the first six months. Timing needs a technical program.'), C('برنامج الإنشاء', 'Construction program', 'البناء وتجاوز التكلفة المفترض موزعان بالتساوي بين الشهر الثالث والثامن عشر. تعديل عدد الوحدات لا يعيد تسعير البناء تلقائيًا؛ تعدل التكلفة والمساحة معًا.', 'Construction and assumed overrun are spread equally across months three to eighteen. Changing unit count does not automatically recost construction; revise costs and areas together.'), C('الإتمام والتأخير', 'Closing and delay', 'توزع المبيعات كوحدات صحيحة على ستة أشهر بدءًا من الشهر التاسع عشر. التأخير يؤخر الإتمام ويزيد أشهر الإدارة؛ تأخر البناء نفسه يحتاج إعادة توزيع صرف مستقلة.', 'Whole-unit sales are spread over six months starting in month nineteen. Delay shifts closing and adds overhead months; construction delay itself needs a separate rescheduling of expenditure.')],
    capacityNote: L('يبني النموذج جميع الوحدات المخططة ولو بيع بعضها فقط. تغيير العدد لا يعني صلاحية تخطيطية أو فنية. لا تُعد الوحدات المتبقية خسارة محاسبية تلقائيًا؛ المعروض فائض نقدي قبل تقييم المخزون المتبقي.', 'All planned units are built even when only some sell. Changing the count establishes no planning or technical feasibility. Unsold units are not automatically accounting losses; the output is cash surplus before valuing remaining inventory.'),
    collectionNote: L('لا تحصيل قبل إتمام البيع، ولا سحب قروض أو فوائد أو دفعات مشترين. يبدأ الرصيد بالتمويل المدخل وتخصم منه جميع تكاليف المشروع بحسب الجدول. تُقارن فجوة التمويل بالرصيد المتاح، لا بالفائض النهائي فقط.', 'There are no pre-closing receipts, loan draws, interest or buyer advances. Cash starts with entered funding and deducts all scheduled project costs. Compare funding gaps against available cash, not just final surplus.'),
    assumptions: [C('أرض وسعر افتراضيان', 'Hypothetical land and price', 'كل مبالغ الأرض والبناء والبيع افتراضات تعليمية غير مرتبطة بعقار معروف. يعتمد مدير التطوير نسخًا جديدة بعد الفحص والتقييم وعروض الكميات.', 'All land, construction and selling amounts are illustrative and unrelated to a known property. The development manager revises them after due diligence, valuation and quantity quotations.'), C('صرف وتحصيل', 'Payments and receipts', 'التوزيع الشهري تبسيط وليس عقد مقاول أو مبيعات. يعاد بناؤه من المستخلصات والاحتجازات والضمانات ومواعيد الإتمام الفعلية.', 'Monthly phasing is a simplification, not a construction or sales contract. Rebuild it from progress payments, retentions, warranties and actual closing dates.')],
    variableCosts: L('يُصرف تجاوز البناء المفترض كاملًا مع أعمال الإنشاء، وليس احتياطيًا نقديًا متاحًا مرة ثانية. تكلفة البيع نسبة من الوحدات المباعة فقط. تبقى تكلفة بناء جميع الوحدات ضمن الصرف حتى عند انخفاض المبيعات.', 'The assumed construction overrun is fully spent with construction, not counted again as available cash. Selling cost applies only to sold units; the cost of building all units remains payable when sales fall.'),
    tax: L('لا تطبق الحاسبة ضريبة قيمة مضافة تجزئة على بيع الوحدات. بند الضرائب مبلغ نقدي افتراضي مستقل يشمل ما يتحمله المشروع من ضرائب غير مستردة؛ وللتحفظ يفترض دفعه كاملًا في الشهر الأول. ليس حسابًا نظاميًا للضريبة ولا يثبت استحقاق إعفاء أو استرداد؛ يستبدل بجدول معاملات مع مختص وفق نوع الأرض والتصرف والأطراف.', 'The calculator does not apply retail VAT to unit sales. The tax line is a separate hypothetical cash allowance for project-borne non-recoverable taxes, conservatively paid entirely in month one. It is not a statutory tax calculation or proof of exemption/refund eligibility; replace it with a specialist-reviewed transaction schedule.'),
    risks: [C('زيادة تكلفة أو تعطل', 'Overrun or interruption', 'المؤشر: فروقات كميات أو مستخلصات أعلى من الخطة. الإجراء: ضبط نطاق فني واحتياطي وتمويل متاح وتقارير مهندس مستقل.', 'Signal: quantity changes or payments exceed plan. Response: controlled technical scope, contingency, available funding and independent engineer reporting.'), C('بيع أبطأ أو بسعر أقل', 'Slower or lower-priced sales', 'المؤشر: طلب غير مؤهل أو حجوزات لا تتم. الإجراء: اختبار خصم السعر وعدد الوحدات والتأخير معًا، دون افتراض بيع كامل المشروع في كل سيناريو.', 'Signal: unqualified interest or reservations that fail to close. Response: jointly test price reductions, sold units and delay rather than assuming sellout in every case.')],
    gates: [C('بوابة الاستثمار', 'Investment gate', 'ملكية وتنظيم وتراخيص قابلة للتحقق، تكلفة موثقة، ومقارنات بيع مناسبة. لا يُعتمد رقم نهائي قبل تحديد أرض ومساحات ومواصفات.', 'Require verifiable title, zoning and permit feasibility, documented costs and relevant sales comparables. No final figure should be approved without a specific site, areas and specifications.'), C('بوابة التمويل', 'Funding gate', 'تغطية أكبر عجز نقدي مع هامش للأحداث غير الممثلة، ثم اختبار السيناريو المتحفظ. إن لم تتوفر السيولة يُعدل نطاق المشروع أو يؤجل، حتى لو كان الفائض الأساسي موجبًا.', 'Cover peak cash deficit plus a buffer for unmodeled events, then test the conservative case. Resize or defer if cash is unavailable, even when base surplus is positive.')],
    brand: [C('رحابة قابلة للإثبات', 'Verifiable spaciousness', 'تربط الهوية وعد المساحة والخصوصية بمخطط ومقاس وضوء موضحين، مع تمييز التصور عن المواصفة المعتمدة.', 'Connect space and privacy promises to explained plans, dimensions and daylight, distinguishing concepts from approved specifications.'), C('أولوية المبيعات والتسليم', 'Sales and handover priorities', 'بطاقة وحدة ومخطط واضح وجدول مواصفات وتكلفة تملك ومسار زيارة وتسليم؛ ثم الحملة بعد تثبيت المنتج وما يجوز عرضه.', 'Prioritize unit sheets, plans, specifications, ownership costs, viewings and handover, then campaigns once the product and permissible claims are established.')],
    sources: [method, { title: L('الزكاة والضريبة والجمارك — نظام التصرفات العقارية', 'ZATCA — Real Estate Transaction Tax law'), url: 'https://www.zatca.gov.sa/ar/RulesRegulations/Taxes/Pages/RETTRegulation.aspx', purpose: L('مرجع رسمي يميز ضريبة التصرفات العقارية عن القيمة المضافة؛ لا يثبت مبلغ مخصص الضرائب في المثال.', 'Official reference distinguishing RETT from VAT; it does not substantiate the example tax allowance.') }, { title: L('تسجيل وإثبات التصرف العقاري', 'Real estate transaction registration'), url: 'https://zatca.gov.sa/ar/eServices/Pages/VatRequest.aspx', purpose: L('مرجع لتسجيل التصرف والتحقق من خضوعه قبل الإتمام بحسب بياناته؛ تُراجع الحالة الفعلية مع مختص.', 'Reference for registration and checking tax treatment before closing using transaction details; a specialist must review the actual case.') }],
  },
];

export function getPortfolioFeasibility(slug: string): PortfolioFeasibilityStudy {
  const study = PORTFOLIO_FEASIBILITY.find(item => item.slug === slug);
  if (!study) throw new Error(`Unknown feasibility study: ${slug}`);
  return study;
}
